/**
 * Generated by `loom add primitive`. Edit the definitions, not this file — it is
 * rewritten from the contents of this directory every time a primitive is added.
 */

import { createPrimitiveRegistry, describeRegistryError } from "@jam-overture/loom/sdk"

import { appPage } from "./app.page.js"

const built = createPrimitiveRegistry([
  appPage,
])

if (!built.ok) {
  throw new Error(`loom: the primitive registry was refused — ${describeRegistryError(built.error)}`)
}

export const registry = built.value
