import { describe, expect, it } from "vitest"

import { auditRegistry, describeRegistryAudit } from "@loom/runtime/sdk"

import { registry } from "./registry.js"

/**
 * Generated by `loom init`. Keep it: a primitive that ignores `loom.editable`
 * renders perfectly and is invisible to the portal, with no error anywhere. This
 * is the only thing that catches it, and it catches it at build time rather than
 * when someone is trying to edit a page.
 */
describe("the primitive registry", () => {
  it("registers primitives that are all visible to the portal", () => {
    const audit = auditRegistry(registry)

    expect(audit.notDecorated, describeRegistryAudit(audit)).toEqual([])
  })

  /**
   * `not-probeable` is neither a pass nor a failure — a hook-using or class
   * component cannot be called outside a renderer. Assert the list you expect so
   * a newly unprobeable primitive is a decision rather than a surprise.
   */
  it("has no primitives the probe could not judge", () => {
    const audit = auditRegistry(registry)

    expect(audit.notProbeable, describeRegistryAudit(audit)).toEqual([])
  })

  /**
   * The one that stops a page rather than a portal: a component that throws on a
   * value its own schema accepts is one a tree the validator *accepted* can take
   * down. If you add a hook-using primitive, the probe cannot tell it from a
   * broken one and it will appear here — narrow this to the entries with
   * `everyConfiguration: false`, which are the ones the audit is certain of.
   */
  it("has no primitives that throw on props their own schema accepts", () => {
    const audit = auditRegistry(registry)

    expect(audit.throwsOnDeclaredProps, describeRegistryAudit(audit)).toEqual([])
  })
})
