import { describe, expect, it } from "vitest"

import { primitiveTypeSchema } from "../primitive-type.js"

import {
  conformanceTest,
  namesFor,
  primitiveModule,
  registryModule,
  RESERVED_PRIMITIVE_TYPES,
} from "./templates.js"

describe("namesFor", () => {
  it("names the module after the type verbatim, so the type round-trips", () => {
    expect(namesFor("commerce.product-card")).toEqual({
      type: "commerce.product-card",
      module: "commerce.product-card.ts",
      exportName: "commerceProductCard",
    })
  })

  it("camel-cases across both separators", () => {
    expect(namesFor("loom.card").exportName).toBe("loomCard")
    expect(namesFor("buy-button").exportName).toBe("buyButton")
    expect(namesFor("a.b-c.d").exportName).toBe("aBCD")
  })
})

describe("primitiveModule", () => {
  const generated = primitiveModule(namesFor("commerce.product-card"))

  it("declares the type it was asked for", () => {
    expect(generated).toContain(`type: "commerce.product-card"`)
    expect(generated).toContain("export const commerceProductCard = definePrimitive({")
  })

  /** The scaffold's whole job is to satisfy §4's contract from the first commit. */
  it("satisfies the contract it is scaffolding", () => {
    expect(generated).toContain("description:")
    expect(generated).toContain("props,")
    expect(generated).toContain("slots: []")
    expect(generated).toContain("...loom.editable")
  })

  it("declares props strictly, so an AI-authored extra prop is refused", () => {
    expect(generated).toContain("z.object({}).strict()")
  })

  it("leaves no placeholder that has to be resolved before it compiles", () => {
    expect(generated).not.toContain("TODO")
    expect(generated).not.toContain("FIXME")
  })
})

describe("registryModule", () => {
  it("imports and registers every primitive, name-sorted for a stable diff", () => {
    const generated = registryModule([namesFor("loom.page"), namesFor("commerce.buy-button")])

    expect(generated.indexOf("commerce.buy-button.js")).toBeLessThan(generated.indexOf("loom.page.js"))
    expect(generated).toContain("  commerceBuyButton,")
    expect(generated).toContain("  loomPage,")
  })

  it("says it is generated, and where to edit instead", () => {
    expect(registryModule([namesFor("loom.page")])).toContain("Generated by `loom add primitive`")
  })

  /** Registration is fallible, so the generated module must not ignore the Result. */
  it("throws with a described error rather than exporting an unbuilt registry", () => {
    const generated = registryModule([namesFor("loom.page")])

    expect(generated).toContain("if (!built.ok)")
    expect(generated).toContain("describeRegistryError(built.error)")
    expect(generated).toContain("export const registry = built.value")
  })

  it("emits a valid module for an empty registry rather than a dangling import", () => {
    const generated = registryModule([])

    expect(generated).not.toContain("import {  }")
    expect(generated).toContain("createPrimitiveRegistry([")
  })
})

describe("conformanceTest", () => {
  it("runs the audit rather than only making it available", () => {
    const generated = conformanceTest()

    expect(generated).toContain("auditRegistry(registry)")
    expect(generated).toContain("audit.notDecorated")
    expect(generated).toContain("audit.notProbeable")
    expect(generated).toContain("describeRegistryAudit(audit)")
  })
})

describe("RESERVED_PRIMITIVE_TYPES", () => {
  /**
   * Each reserved name is reserved *because* it is a valid primitive type — an
   * invalid one would already be refused and would not need reserving.
   */
  it("reserves only names the tree schema would otherwise accept", () => {
    for (const type of RESERVED_PRIMITIVE_TYPES) {
      expect(primitiveTypeSchema.safeParse(type).success).toBe(true)
    }
  })
})
