/**
 * What the CLI writes, as pure functions of a name.
 *
 * Every template is a string a host will read, edit, and keep, so they are held
 * to the same standard as the runtime: no dead imports, no placeholder that
 * typechecks only after a rewrite, and a generated file that says it is
 * generated. A scaffold that has to be repaired before it compiles teaches the
 * wrong thing about the contract on the first contact with it.
 */

export type PrimitiveNames = {
  /** The primitive type, exactly as a tree will address it. */
  readonly type: string
  /**
   * The module basename, which is the type verbatim: `commerce.product-card.ts`.
   *
   * Dots survive where a slug would not. Folding `.` to `-` is lossy — nothing
   * can tell whether `commerce-product-card` was `commerce.product-card` or
   * `commerce-product.card` — and the registry is regenerated from the directory
   * listing, so that round trip has to be exact.
   */
  readonly module: string
  /** The exported binding: `commerce.product-card` → `commerceProductCard`. */
  readonly exportName: string
}

const capitalize = (segment: string): string => `${segment.slice(0, 1).toUpperCase()}${segment.slice(1)}`

const camelCase = (type: string): string => {
  const words = type.split(/[.-]/).filter((word) => word.length > 0)
  const [first, ...rest] = words

  return `${first ?? ""}${rest.map(capitalize).join("")}`
}

export const namesFor = (type: string): PrimitiveNames => ({
  type,
  module: `${type}.ts`,
  exportName: camelCase(type),
})

export const primitiveModule = (names: PrimitiveNames): string => `import { createElement } from "react"
import { z } from "zod"

import type { LoomPrimitiveProps } from "@loom/runtime/react"
import { definePrimitive } from "@loom/runtime/sdk"

/**
 * Every prop a tree may set on this primitive. The render seam refuses a node
 * whose props do not satisfy this schema, so it is the one place that decides
 * what AI is allowed to configure here.
 */
const props = z.object({}).strict()

type Props = z.infer<typeof props>

export const ${names.exportName} = definePrimitive({
  type: "${names.type}",
  /** One line. This is what a model reads when choosing between primitives. */
  description: "Describe what ${names.type} is for",
  props,
  /** Name a slot here for every region this primitive projects children into. */
  slots: [],
  component: ({ loom, children }: LoomPrimitiveProps<Props>) =>
    /**
     * Spreading \`loom.editable\` is the edit-mode contract: without it this
     * primitive renders correctly and is invisible to the portal. Read declared
     * props off the \`props\` bag — they are never spread onto the element.
     */
    createElement("div", { ...loom.editable }, children),
})
`

export const REGISTRY_MODULE = "registry.ts"
export const CONFORMANCE_TEST_MODULE = "registry.test.ts"

/**
 * Reserved because the registry and its test share the primitives directory, and
 * `registry` and `registry.test` are both valid primitive types — so a primitive
 * named either one would be written over the file that registers it.
 */
export const RESERVED_PRIMITIVE_TYPES: readonly string[] = ["registry", "registry.test"]

export const registryModule = (primitives: readonly PrimitiveNames[]): string => {
  const sorted = [...primitives].sort((left, right) => left.type.localeCompare(right.type))

  const imports = sorted
    .map((names) => `import { ${names.exportName} } from "./${names.type}.js"`)
    .join("\n")

  const registered = sorted.map((names) => `  ${names.exportName},`).join("\n")

  return `/**
 * Generated by \`loom add primitive\`. Edit the definitions, not this file — it is
 * rewritten from the contents of this directory every time a primitive is added.
 */

import { createPrimitiveRegistry, describeRegistryError } from "@loom/runtime/sdk"
${imports === "" ? "" : `\n${imports}\n`}
const built = createPrimitiveRegistry([
${registered}
])

if (!built.ok) {
  throw new Error(\`loom: the primitive registry was refused — \${describeRegistryError(built.error)}\`)
}

export const registry = built.value
`
}

/**
 * The generated test is the point of the generated scaffold. `auditRegistry`
 * reports and never enforces (0012), so a deployment only benefits from it if
 * something actually runs it — and a host is far more likely to keep a test that
 * was there from the first commit than to add one later.
 */
export const conformanceTest = (): string => `import { describe, expect, it } from "vitest"

import { auditRegistry, describeRegistryAudit } from "@loom/runtime/sdk"

import { registry } from "./registry.js"

/**
 * Generated by \`loom init\`. Keep it: a primitive that ignores \`loom.editable\`
 * renders perfectly and is invisible to the portal, with no error anywhere. This
 * is the only thing that catches it, and it catches it at build time rather than
 * when someone is trying to edit a page.
 */
describe("the primitive registry", () => {
  it("registers primitives that are all visible to the portal", () => {
    const audit = auditRegistry(registry)

    expect(audit.notDecorated, describeRegistryAudit(audit)).toEqual([])
  })

  /**
   * \`not-probeable\` is neither a pass nor a failure — a hook-using or class
   * component cannot be called outside a renderer. Assert the list you expect so
   * a newly unprobeable primitive is a decision rather than a surprise.
   */
  it("has no primitives the probe could not judge", () => {
    const audit = auditRegistry(registry)

    expect(audit.notProbeable, describeRegistryAudit(audit)).toEqual([])
  })
})
`
