/*
 * 6 code blocks from /docs/building-with-loom/theming, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/building-with-loom/theming/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { STARTER_PALETTES, createThemeRegistry, paletteScheme } from "@jam-overture/loom"
import type { LoomTree, ResolvedTheme } from "@jam-overture/loom"
import { renderLoomTree, themeGround, themeStyle } from "@jam-overture/loom/react"

import {
  ourDarkPalette,
  ourFontPack,
  ourLightPalette,
  ourStylePreset,
  registry,
  theme,
} from "../context/building-with-loom--theming"

// page.mdx:29 — the inside of an object literal
const objectAtLine29 = {
props: {
  "loom:theme": {
    palette: "tide",
    fontPack: "grotesque",
    stylePreset: "technical",
  },
}
}

// page.mdx:162 — a program
const themes = createThemeRegistry({
  palettes: [ourLightPalette, ourDarkPalette],
  fontPacks: [ourFontPack],
  stylePresets: [ourStylePreset],
})

// page.mdx:182 — a program
createThemeRegistry({ palettes: [...STARTER_PALETTES, ourLightPalette] })

// page.mdx:247 — a program
const Excerpt = ({ tree, theme }: { tree: LoomTree; theme: ResolvedTheme }) => (
  <div style={{ ...themeStyle(theme), ...themeGround(theme) }}>
    {renderLoomTree(tree, { resolver: registry, validator: registry }).element}
  </div>
)

// page.mdx:277 — a program
const scheme = paletteScheme(theme.palette)

// page.mdx:346 — a program
const MARKS = { light: "/mark-on-light.svg", dark: "/mark-on-dark.svg" } as const

const markFor = (resolved: ResolvedTheme): string | undefined => {
  const scheme = paletteScheme(resolved.palette)

  return scheme === undefined ? undefined : MARKS[scheme]
}

export { objectAtLine29, themes, Excerpt, scheme, MARKS, markFor, createThemeRegistry, STARTER_PALETTES, paletteScheme, renderLoomTree, themeGround, themeStyle }
export type { LoomTree, ResolvedTheme }
