/*
 * 2 code blocks from /docs/building-with-loom/what-ai-may-change, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/building-with-loom/what-ai-may-change/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { fixedPolicy, gatePolicySchema } from "@loom/runtime"
import type { CompositionRuntime } from "@loom/runtime"

import { clock, events, idFactory, interpreter } from "../context/building-with-loom--what-ai-may-change"

// page.mdx:20 — a program
export const policy = gatePolicySchema.parse({
  policyId: "acme-storefront-2026-09",
  protectedPrimitiveTypes: ["commerce.checkout", "commerce.price-tag"],
})

// page.mdx:160 — a program
const runtime: CompositionRuntime = {
  interpreter,
  policySource: fixedPolicy(policy),
  events,
  clock,
  idFactory,
}

export { runtime, gatePolicySchema, fixedPolicy }
export type { CompositionRuntime }
