/*
 * 5 code blocks from /docs/building-with-loom/primitives, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/building-with-loom/primitives/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { createElement } from "react"
import { z } from "zod"
import {
  createPrimitiveRegistry,
  definePrimitive,
  describeRegistryError,
  selectPrimitives,
} from "@jam-overture/loom/sdk"
import type { LoomPrimitiveProps } from "@jam-overture/loom/react"
import { STARTER_PRIMITIVES, createStarterPrimitiveRegistry } from "@jam-overture/loom/primitives"

import { heading, statGrid } from "../context/building-with-loom--primitives"

// page.mdx:16 — a program
const props = z
  .object({
    value: z.string().min(1).max(24),
    label: z.string().min(1).max(80),
    caption: z.string().min(1).max(160).optional(),
  })
  .strict()

type Props = z.infer<typeof props>

export const stat = definePrimitive({
  type: "loom.stat",
  description: "A single figure with a short label — one cell of a loom.stat-grid.",
  props,
  slots: [],
  component: ({ loom, props: given }: LoomPrimitiveProps<Props>) =>
    createElement("div", { ...loom.editable }, given.value, given.label),
})

// page.mdx:101 — the inside of an object literal
const objectAtLine101 = {
text: { excluded: "Not included" }
}

// page.mdx:111 — a program
const built = createPrimitiveRegistry([stat, statGrid, heading])

if (!built.ok) throw new Error(describeRegistryError(built.error))

// page.mdx:149 — a program
const chosen = selectPrimitives(STARTER_PRIMITIVES, ["loom.hero", "loom.prose"])

export { props, objectAtLine101, built, chosen, createElement, z, definePrimitive, createPrimitiveRegistry, describeRegistryError, selectPrimitives, createStarterPrimitiveRegistry, STARTER_PRIMITIVES }
export type { Props, LoomPrimitiveProps }
