/*
 * 4 code blocks from /docs/building-with-loom/composition, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/building-with-loom/composition/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import {
  buildElement,
  buildSlot,
  createElement,
  features,
  heading,
  hero,
  ids,
  pricing,
  primaryAction,
  prose,
  secondaryAction,
} from "../context/building-with-loom--composition"
import type { LoomPrimitiveProps } from "../context/building-with-loom--composition"

// page.mdx:21 — a program
buildElement(ids, {
  type: "loom.page",
  children: [hero, features, pricing],
})

// page.mdx:37 — a program
buildElement(ids, {
  type: "loom.hero",
  props: { align: "center", eyebrow: "The AI-native UI runtime" },
  children: [
    buildSlot(ids, "heading", [heading(ids, 1, "Your AI can change this page")]),
    prose(ids, "And you can see exactly what it changed."),
    buildSlot(ids, "actions", [primaryAction, secondaryAction]),
  ],
})

// page.mdx:52 — the inside of an object literal
const objectAtLine52 = {
component: ({ loom, children }: LoomPrimitiveProps) =>
  createElement(
    "section",
    { ...loom.editable },
    loom.slots["heading"],
    createElement("div", { className: "body" }, children),
    loom.slots["actions"]
  )
}

// page.mdx:70 — the inside of an object literal
const objectAtLine70 = {
slots: ["heading", "actions", "media"]
}

export { objectAtLine52, objectAtLine70 }
