/*
 * 5 code blocks from /docs/building-with-loom/where-content-comes-from, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/building-with-loom/where-content-comes-from/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { z } from "zod"
import { createDataRegistry, defineSource, describeDataRegistryError, resolveTreeData } from "@loom/runtime"
import { renderLoomTree } from "@loom/runtime/react"
import type { LoomPrimitiveProps } from "@loom/runtime/react"
import { createElement } from "react"
import { definePrimitive } from "@loom/runtime/sdk"

import { db, page, primitives } from "../context/building-with-loom--where-content-comes-from"

// page.mdx:35 — the inside of an object literal
const objectAtLine35 = {
"loom:data": {
  services: { source: "catalogue.services", params: { tag: "baking", limit: 3 } },
}
}

// page.mdx:76 — a program
const services = defineSource({
  id: "catalogue.services",
  description: "What this shop offers, most popular first.",
  params: z.object({
    tag: z.string().min(1).max(40),
    limit: z.number().int().min(1).max(12),
  }),
  answers: z.array(z.object({ name: z.string(), price: z.string() })),
  adapter: {
    fetch: async ({ params }) => {
      const rows = await db.services(params.tag, params.limit)

      return { ok: true, value: rows }
    },
  },
})

const built = createDataRegistry([services])

if (!built.ok) throw new Error(describeDataRegistryError(built.error))

const sources = built.value

// page.mdx:139 — a program
const data = await resolveTreeData(page, { registry: sources })

const rendered = renderLoomTree(page, { resolver: primitives, validator: primitives, data })

// page.mdx:221 — a program
const rows = z.array(z.object({ name: z.string(), price: z.string() }))

export const serviceList = definePrimitive({
  type: "shop.service-list",
  description: "The shop's services, read from a catalogue.services binding.",
  props: z.object({}).strict(),
  slots: [],
  component: ({ loom }: LoomPrimitiveProps<Record<string, never>>) => {
    const answer = loom.data["services"]

    if (answer === undefined || answer.status === "unavailable") {
      return createElement("p", loom.editable, "We could not load our services just now.")
    }

    const services = rows.safeParse(answer.value)

    if (!services.success) {
      return createElement("p", loom.editable, "We could not load our services just now.")
    }

    if (services.data.length === 0) {
      return createElement("p", loom.editable, "We have not listed any services yet.")
    }

    return createElement(
      "ul",
      loom.editable,
      services.data.map((service) =>
        createElement("li", { key: service.name }, `${service.name} — ${service.price}`)
      )
    )
  },
})

// page.mdx:300 — the inside of an object literal
const objectAtLine300 = {
protectedPropKeys: ["loom:data"],
}

export { objectAtLine35, services, built, sources, data, rendered, rows, objectAtLine300, z, createDataRegistry, defineSource, describeDataRegistryError, resolveTreeData, renderLoomTree, createElement, definePrimitive }
export type { LoomPrimitiveProps }
