/*
 * 3 code blocks from /docs/building-with-loom/theming, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/building-with-loom/theming/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { STARTER_PALETTES, createThemeRegistry } from "@loom/runtime"

import {
  ourDarkPalette,
  ourFontPack,
  ourLightPalette,
  ourStylePreset,
} from "../context/building-with-loom--theming"

// page.mdx:26 — the inside of an object literal
const objectAtLine26 = {
props: {
  "loom:theme": {
    palette: "tide",
    fontPack: "grotesque",
    stylePreset: "technical",
  },
}
}

const themes = createThemeRegistry({
  palettes: [ourLightPalette, ourDarkPalette],
  fontPacks: [ourFontPack],
  stylePresets: [ourStylePreset],
})

createThemeRegistry({ palettes: [...STARTER_PALETTES, ourLightPalette] })

export { objectAtLine26, themes, createThemeRegistry, STARTER_PALETTES }
