/*
 * 8 code blocks from /docs/building-with-loom/testing-what-you-built, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/building-with-loom/testing-what-you-built/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import {
  buildIntent,
  buildProposal,
  collectingEventSink,
  fixedClock,
  sampleTree,
  scriptedInterpreter,
  testRegistry,
} from "@jam-overture/loom/testing"
import {
  buildElement,
  buildText,
  createThemeRegistry,
  createTree,
  fixedPolicy,
  gatePolicySchema,
  ok,
  sequentialIdFactory,
} from "@jam-overture/loom"
import type { GatePolicy, LoomTree, NodeId } from "@jam-overture/loom"
import { renderLoomTree } from "@jam-overture/loom/react"
import { describe, expect, it } from "vitest"
import { memoryTreeStore } from "@jam-overture/loom/store"
import { commitIntent, memoryHoldStore } from "@jam-overture/loom/write"
import type { WritePath } from "@jam-overture/loom/write"
import { describeTreeStoreContract } from "@jam-overture/loom/testing/contracts"

// page.mdx:45 — a program
const { tree, ids } = sampleTree()

// page.mdx:81 — a program
const registry = testRegistry()

const rendered = renderLoomTree(tree, {
  resolver: registry,
  validator: registry,
  themes: createThemeRegistry(),
})

// page.mdx:118 — a program
it("renders the sample page with nothing to report", () => {
  expect(rendered.diagnostics).toEqual([])
})

// page.mdx:138 — a program
const pricingPage = (): { readonly tree: LoomTree; readonly planId: NodeId } => {
  const ids = sequentialIdFactory("shop")

  const label = buildText(ids, "Starter")
  const plan = buildElement(ids, { type: "shop.plan", props: { price: "£9" }, children: [label] })
  const page = buildElement(ids, { type: "loom.page", props: { title: "Pricing" }, children: [plan] })

  return { tree: createTree(page, ids), planId: plan.id }
}

// page.mdx:158 — a program
const askToRaiseThePrice = async (policy: GatePolicy) => {
  const { tree, planId } = pricingPage()
  const ids = sequentialIdFactory("ask")

  const intent = buildIntent(ids, {
    treeId: tree.treeId,
    baseRevision: tree.revision,
    utterance: "Put the starter plan up to £12",
  })

  const proposal = buildProposal(ids, {
    intentId: intent.intentId,
    delta: {
      deltaId: ids.deltaId(),
      treeId: tree.treeId,
      baseRevision: tree.revision,
      operations: [{ op: "configure", nodeId: planId, set: { price: "£12" }, unset: [] }],
    },
  })

  const store = memoryTreeStore()
  await store.create(tree)

  const path: WritePath = {
    store,
    holds: memoryHoldStore(),
    runtime: {
      interpreter: scriptedInterpreter(ok(proposal)),
      policySource: fixedPolicy(policy),
      events: collectingEventSink(),
      clock: fixedClock(),
      idFactory: ids,
    },
  }

  return commitIntent(path, intent)
}

// page.mdx:214 — a program
describe("the price on a plan", () => {
  it("cannot be changed without a person saying yes", async () => {
    const outcome = await askToRaiseThePrice(
      gatePolicySchema.parse({ policyId: "shop", protectedPropKeys: ["price"] })
    )

    expect(outcome.kind).toBe("held")
  })

  it("is only held because the policy says so", async () => {
    const outcome = await askToRaiseThePrice(gatePolicySchema.parse({ policyId: "shop" }))

    expect(outcome.kind).toBe("committed")
  })
})

// page.mdx:243 — a program
it("says why it was held", async () => {
  const outcome = await askToRaiseThePrice(
    gatePolicySchema.parse({ policyId: "shop", protectedPropKeys: ["price"] })
  )

  if (outcome.kind !== "held") throw new Error("expected a held proposal")

  expect(outcome.held.disposition.reason.detail).toBe("configures protected price")
})

// page.mdx:279 — a program
describeTreeStoreContract("memoryTreeStore", () => memoryTreeStore())

export { tree, ids, registry, rendered, pricingPage, askToRaiseThePrice, sampleTree, testRegistry, buildIntent, buildProposal, collectingEventSink, fixedClock, scriptedInterpreter, createThemeRegistry, buildElement, buildText, createTree, sequentialIdFactory, fixedPolicy, ok, gatePolicySchema, renderLoomTree, expect, it, describe, memoryTreeStore, commitIntent, memoryHoldStore, describeTreeStoreContract }
export type { LoomTree, NodeId, GatePolicy, WritePath }
