/*
 * 7 code blocks from /docs/building-with-loom/starting-from-a-band, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/building-with-loom/starting-from-a-band/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { buildElement, createTree, sequentialIdFactory, systemClock } from "@jam-overture/loom"
import {
  CATALOGUE_TYPES,
  PAGE_SEQUENCE,
  STARTER_PRIMITIVES,
  compositionById,
  compositionInterpreter,
  compositionsForPart,
  planComposition,
} from "@jam-overture/loom/primitives"
import { createPrimitiveRegistry, selectPrimitives } from "@jam-overture/loom/sdk"

// page.mdx:30 — a program
const ids = sequentialIdFactory("page")

const pricing = compositionById("pricing")

if (pricing === undefined) throw new Error("this library has no pricing band")

/* The whole band, with freshly minted ids, and nothing on a page yet. */
const subtree = pricing.build(ids)

// page.mdx:58 — a program
const tree = createTree(buildElement(ids, { type: "loom.page" }), ids)

const plan = planComposition(pricing, tree, ids)

/* One `insert`, carrying the whole subtree — not one operation per node. */
const operations = plan.outcome === "planned" ? plan.operations : []

// page.mdx:92 — a program
const interpreter = compositionInterpreter(pricing, ids, systemClock)

// page.mdx:126 — a program
/* Canonical design first. A part nobody has drawn yet gives you an empty list. */
const heroes = compositionsForPart("hero")

// page.mdx:157 — a program
const wholePage = PAGE_SEQUENCE.map((composition) => composition.build(ids))

// page.mdx:199 — a program
const chosen = selectPrimitives(STARTER_PRIMITIVES, CATALOGUE_TYPES)

const registry = chosen.ok ? createPrimitiveRegistry(chosen.value) : chosen

export { ids, pricing, subtree, tree, plan, operations, interpreter, heroes, wholePage, chosen, registry, sequentialIdFactory, buildElement, createTree, systemClock, compositionById, planComposition, compositionInterpreter, compositionsForPart, PAGE_SEQUENCE, CATALOGUE_TYPES, STARTER_PRIMITIVES, createPrimitiveRegistry, selectPrimitives }
