/*
 * 4 code blocks from /docs/building-with-loom/theming, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/building-with-loom/theming/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { STARTER_PALETTES, createThemeRegistry } from "@jam-overture/loom"
import type { LoomTree, ResolvedTheme } from "@jam-overture/loom"
import { renderLoomTree, themeGround, themeStyle } from "@jam-overture/loom/react"

import {
  ourDarkPalette,
  ourFontPack,
  ourLightPalette,
  ourStylePreset,
  registry,
} from "../context/building-with-loom--theming"

// page.mdx:27 — the inside of an object literal
const objectAtLine27 = {
props: {
  "loom:theme": {
    palette: "tide",
    fontPack: "grotesque",
    stylePreset: "technical",
  },
}
}

// page.mdx:160 — a program
const themes = createThemeRegistry({
  palettes: [ourLightPalette, ourDarkPalette],
  fontPacks: [ourFontPack],
  stylePresets: [ourStylePreset],
})

// page.mdx:179 — a program
createThemeRegistry({ palettes: [...STARTER_PALETTES, ourLightPalette] })

// page.mdx:244 — a program
const Excerpt = ({ tree, theme }: { tree: LoomTree; theme: ResolvedTheme }) => (
  <div style={{ ...themeStyle(theme), ...themeGround(theme) }}>
    {renderLoomTree(tree, { resolver: registry, validator: registry }).element}
  </div>
)

export { objectAtLine27, themes, Excerpt, createThemeRegistry, STARTER_PALETTES, renderLoomTree, themeGround, themeStyle }
export type { LoomTree, ResolvedTheme }
