/*
 * 8 code blocks from /docs/building-with-loom/theming, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/building-with-loom/theming/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { STARTER_PALETTES, createThemeRegistry, paletteScheme } from "@jam-overture/loom"
import type { LoomTree, ResolvedTheme } from "@jam-overture/loom"
import { renderLoomTree, themeGround, themeStyle } from "@jam-overture/loom/react"

import {
  ourDarkPalette,
  ourFontPack,
  ourLightPalette,
  ourStylePreset,
  registry,
  theme,
} from "../context/building-with-loom--theming"

// page.mdx:30 — the inside of an object literal
const objectAtLine30 = {
props: {
  "loom:theme": {
    palette: "tide",
    fontPack: "grotesque",
    stylePreset: "technical",
  },
}
}

// page.mdx:163 — a program
const themes = createThemeRegistry({
  palettes: [ourLightPalette, ourDarkPalette],
  fontPacks: [ourFontPack],
  stylePresets: [ourStylePreset],
})

// page.mdx:183 — a program
createThemeRegistry({ palettes: [...STARTER_PALETTES, ourLightPalette] })

// page.mdx:248 — a program
const Excerpt = ({ tree, theme }: { tree: LoomTree; theme: ResolvedTheme }) => (
  <div style={{ ...themeStyle(theme), ...themeGround(theme) }}>
    {renderLoomTree(tree, { resolver: registry, validator: registry }).element}
  </div>
)

// page.mdx:278 — a program
const scheme = paletteScheme(theme.palette)

// page.mdx:352 — a program
const MARKS = { light: "/mark-on-light.svg", dark: "/mark-on-dark.svg" } as const

const markFor = (resolved: ResolvedTheme): string | undefined => {
  const scheme = paletteScheme(resolved.palette)

  return scheme === undefined ? undefined : MARKS[scheme]
}

// page.mdx:386 — a program
const ThemeColor = ({ resolved }: { resolved: ResolvedTheme }) => {
  const ground = themeGround(resolved)

  return ground === undefined ? null : <meta name="theme-color" content={ground.backgroundColor} />
}

// page.mdx:410 — a program
const theFormEverybodyShows = (
  <>
    <meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff" />
    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#111827" />
  </>
)

export { objectAtLine30, themes, Excerpt, scheme, MARKS, markFor, ThemeColor, theFormEverybodyShows, createThemeRegistry, STARTER_PALETTES, paletteScheme, renderLoomTree, themeGround, themeStyle }
export type { LoomTree, ResolvedTheme }
