/*
 * 4 code blocks from /docs/getting-started/rendering-a-tree, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/getting-started/rendering-a-tree/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { createThemeRegistry } from "@loom/runtime"
import { createStarterPrimitiveRegistry } from "@loom/runtime/primitives"
import { renderLoomTree } from "@loom/runtime/react"

import {
  notFound,
  options,
  renderRequest,
  request,
  resolver,
  source,
  themes,
  tree,
  validator,
} from "../context/getting-started--rendering-a-tree"

// page.mdx:10 — the inside of a function
const functionAtLine10 = async () => {
const registry = createStarterPrimitiveRegistry()

if (!registry.ok) throw new Error("the registry was refused")

const rendered = renderLoomTree(tree, {
  resolver: registry.value,
  validator: registry.value,
  themes: createThemeRegistry(),
})

return <main>{rendered.element}</main>
}

// page.mdx:43 — a program
const { element, diagnostics, theme } = renderLoomTree(tree, options)

// page.mdx:69 — the inside of an object literal
const objectAtLine69 = {
props: {
  "loom:theme": {
    palette: "minimal",
    fontPack: "minimal-sans",
    stylePreset: "precise",
  },
}
}

// page.mdx:114 — the inside of a function
const functionAtLine114 = async () => {
const served = await renderRequest(request, { source, resolver, validator, themes })

if (!served.ok) return notFound()

return <main>{served.value.element}</main>
}

export { functionAtLine10, element, diagnostics, theme, objectAtLine69, functionAtLine114, createThemeRegistry, createStarterPrimitiveRegistry, renderLoomTree }
