/*
 * 3 code blocks from /docs/getting-started/your-first-tree, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/getting-started/your-first-tree/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { buildElement, buildText, createTree, parseTree, sequentialIdFactory } from "@loom/runtime"

import { reject, request } from "../context/getting-started--your-first-tree"

const ids = sequentialIdFactory("firsttree")

const tree = createTree(
  buildElement(ids, {
    type: "loom.page",
    props: {
      width: "readable",
      "loom:theme": {
        palette: "minimal",
        fontPack: "minimal-sans",
        stylePreset: "precise",
      },
    },
    children: [
      buildElement(ids, {
        type: "loom.heading",
        props: { level: 1 },
        children: [buildText(ids, "Hello from a tree")],
      }),
      buildElement(ids, {
        type: "loom.prose",
        children: [buildText(ids, "Nothing here was written as markup.")],
      }),
    ],
  }),
  ids
)

// page.mdx:107 — a program
tree.treeId

//        t_firsttree1 — what a store keys it by
tree.revision

//      0 — every applied change increments this
tree.schemaVersion

// the shape of everything above
tree.root

// page.mdx:124 — the inside of a function
const functionAtLine124 = async () => {
const parsed = parseTree(await request.json())

if (!parsed.ok) return reject(parsed.error)
}

export { ids, tree, functionAtLine124, buildElement, buildText, createTree, sequentialIdFactory, parseTree }
