/*
 * 1 code block from /docs/getting-started/installation, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/getting-started/installation/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { createStarterPrimitiveRegistry } from "@jam-overture/loom/primitives"
import { describeRegistryError } from "@jam-overture/loom/sdk"

// page.mdx:70 — a program
const built = createStarterPrimitiveRegistry()

if (!built.ok) {
  throw new Error(`the registry was refused — ${describeRegistryError(built.error)}`)
}

const registry = built.value

export { built, registry, createStarterPrimitiveRegistry, describeRegistryError }
