/*
 * 2 code blocks from /docs/getting-started/your-first-change, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/getting-started/your-first-change/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { commitIntent, confirmHeld } from "@jam-overture/loom/write"

import { intent, path, proposalId, reviewer } from "../context/getting-started--your-first-change"

// page.mdx:83 — a program
const outcome = await commitIntent(path, intent)

switch (outcome.kind) {
  case "committed":
    // The Gate said yes. Show the page it handed back.
    break
  case "held":
    // A person has to answer. Put it in front of them and keep its id.
    break
  case "refused":
    // The Gate said no. Tell the asker why, in the Gate's own words.
    break
}

// page.mdx:104 — a program
const answered = await confirmHeld(path, { proposalId, actor: reviewer.id })

export { outcome, answered, commitIntent, confirmHeld }
