/*
 * 3 code blocks from /docs/the-runtime/when-something-looks-wrong, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/the-runtime/when-something-looks-wrong/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { attributeTree, auditSnapshot } from "@loom/runtime/store"

import { holds, page, seed, store, treeId } from "../context/the-runtime--when-something-looks-wrong"

// page.mdx:58 — a program
const attributed = await attributeTree(store, page)

// page.mdx:117 — a program
const audited = await auditSnapshot(store, treeId, seed)

// page.mdx:157 — a program
const waiting = await holds.forTree(treeId)

export { attributed, audited, waiting, attributeTree, auditSnapshot }
