/*
 * 3 code blocks from /docs/the-runtime/what-your-app-has-to-do, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/the-runtime/what-your-app-has-to-do/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { fixedPolicy, randomIdFactory, systemClock } from "@loom/runtime"
import { postgresHoldStore, postgresTreeStore } from "@loom/runtime/postgres"
import { commitIntent, confirmHeld, discardHeld } from "@loom/runtime/write"
import type { WritePath } from "@loom/runtime/write"

import {
  db,
  events,
  interpreter,
  page,
  policy,
  proposalId,
  reviewer,
  session,
} from "../context/the-runtime--what-your-app-has-to-do"
import type { EditIntent } from "../context/the-runtime--what-your-app-has-to-do"

const path: WritePath = {
  store: postgresTreeStore(db),
  holds: postgresHoldStore(db),
  runtime: {
    interpreter,
    policySource: fixedPolicy(policy),
    events,
    clock: systemClock,
    idFactory: randomIdFactory,
  },
}

// page.mdx:68 — a program
const intent: EditIntent = {
  intentId: randomIdFactory.intentId(),
  treeId: page.treeId,
  baseRevision: page.revision,
  origin: "user-instruction",
  actor: session.userId,
  utterance: "Make the heading on this page smaller",
  observedAt: systemClock.now(),
}

const outcome = await commitIntent(path, intent)

const yes = await confirmHeld(path, { proposalId, actor: reviewer.id })

const no = await discardHeld(path, { proposalId, actor: reviewer.id })

export { path, intent, outcome, yes, no, fixedPolicy, randomIdFactory, systemClock, postgresHoldStore, postgresTreeStore, commitIntent, confirmHeld, discardHeld }
export type { WritePath }
