/*
 * 3 code blocks from /docs/the-runtime/what-a-form-posts-to, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/the-runtime/what-a-form-posts-to/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import {
  createEndpointRegistry,
  defineEndpoint,
  describeEndpointRegistryError,
  resolveTreeSubmissions,
} from "@loom/runtime"
import { renderLoomTree } from "@loom/runtime/react"

import { resolver, themes, tokens, tree, validator } from "../context/the-runtime--what-a-form-posts-to"

// page.mdx:47 — the inside of an object literal
const objectAtLine47 = {
"loom:submit": { "to": "contact.enquiry" },
}

// page.mdx:69 — a program
const enquiry = defineEndpoint({
  id: "contact.enquiry",
  description: "Sends an enquiry to the team's shared inbox.",
  endpoint: {
    /** Called once per page that has this form on it, before anything is drawn. */
    target: async ({ context, signal }) => {
      const token = await tokens.mint(context, { signal })

      return {
        ok: true,
        value: {
          action: "/contact",
          method: "post",
          fields: [{ name: "csrf", value: token }],
        },
      }
    },
  },
})

const built = createEndpointRegistry([enquiry])

if (!built.ok) throw new Error(describeEndpointRegistryError(built.error))

const endpoints = built.value

// page.mdx:138 — a program
const submissions = await resolveTreeSubmissions(tree, { registry: endpoints })

const { element } = renderLoomTree(tree, { resolver, validator, themes, submissions })

export { objectAtLine47, enquiry, built, endpoints, submissions, element, createEndpointRegistry, defineEndpoint, describeEndpointRegistryError, resolveTreeSubmissions, renderLoomTree }
