/*
 * 2 code blocks from /docs/the-runtime/what-the-gate-decides, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/the-runtime/what-the-gate-decides/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import {
  docsRegistry,
  gatePolicySchema,
  interactiveTypesFor,
} from "../context/the-runtime--what-the-gate-decides"

// page.mdx:61 — a program
const policy = gatePolicySchema.parse({
  policyId: "acme-storefront",
  protectedPrimitiveTypes: ["commerce.checkout", "legal.consent-notice"],
  protectedPropKeys: ["price"],
})

// page.mdx:72 — a program
const docsGatePolicy = gatePolicySchema.parse({
  policyId: "loom-docs",
  protectedPrimitiveTypes: ["loom.heading"],
  interactiveTypes: interactiveTypesFor(docsRegistry),
})

export { policy, docsGatePolicy }
