/*
 * 3 code blocks from /docs/the-runtime/going-to-production, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/the-runtime/going-to-production/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { memoryTreeStore } from "@jam-overture/loom/store"
import { memoryHoldStore } from "@jam-overture/loom/write"
import { memoryTelemetryJournal } from "@jam-overture/loom/telemetry"
import { drizzle } from "drizzle-orm/postgres-js"
import postgres from "postgres"
import { ensureHoldStoreSchema, ensureTreeStoreSchema } from "@jam-overture/loom/postgres"
import { ensureTelemetrySchema } from "@jam-overture/loom/telemetry/postgres"

// page.mdx:38 — a program
// This site, and `pnpm dev`.
const trees = memoryTreeStore()

const holds = memoryHoldStore()

const journal = memoryTelemetryJournal()

// page.mdx:93 — a program
const url = process.env.DATABASE_URL

if (url === undefined) throw new Error("DATABASE_URL is not set")

const db = drizzle(postgres(url, { prepare: false, max: 1 }))

// page.mdx:131 — a program
await ensureTreeStoreSchema(db)

await ensureHoldStoreSchema(db)

await ensureTelemetrySchema(db)

export { trees, holds, journal, url, db, memoryTreeStore, memoryHoldStore, memoryTelemetryJournal, drizzle, postgres, ensureTreeStoreSchema, ensureHoldStoreSchema, ensureTelemetrySchema }
