/*
 * 3 code blocks from /docs/the-runtime/when-nothing-comes-back, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/the-runtime/when-nothing-comes-back/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import {
  defineSource,
  modelInterpreter,
  randomIdFactory,
  resolveTreeData,
  systemClock,
} from "@jam-overture/loom"
import { z } from "zod"
import { hangingModelClient } from "@jam-overture/loom/testing"

import { client, db, intent, registry, tree } from "../context/the-runtime--when-nothing-comes-back"

// page.mdx:117 — a program
/** An interpretation you know is long. Ten minutes instead of three. */
export const interpreter = modelInterpreter({
  client,
  idFactory: randomIdFactory,
  clock: systemClock,
  ceilingMs: 600_000,
})

/** A page whose reader will not wait ten seconds. Three instead. */
export const answers = await resolveTreeData(tree, { registry, ceilingMs: 3_000 })

// page.mdx:149 — a program
export const deliveries = defineSource({
  id: "courier.tracking",
  description: "Where a delivery has got to.",
  params: z.object({ order: z.string().min(1) }),
  answers: z.array(z.string()),
  adapter: {
    /** The signal is the half people forget. Hand it to the thing that waits. */
    fetch: async ({ params, signal }) => {
      const stops = await db.deliveries.find(params.order, { signal })

      return { ok: true, value: stops }
    },
  },
})

// page.mdx:179 — a program
const neverReplies = hangingModelClient()

const bounded = modelInterpreter({
  client: neverReplies,
  idFactory: randomIdFactory,
  clock: systemClock,
  /** Milliseconds, so a test that covers this finishes like any other test. */
  ceilingMs: 50,
})

const outcome = await bounded.interpret(intent, tree)

export { neverReplies, bounded, outcome, modelInterpreter, randomIdFactory, resolveTreeData, systemClock, defineSource, z, hangingModelClient }
