/*
 * 2 code blocks from /docs/the-runtime/answering-a-held-change, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/the-runtime/answering-a-held-change/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { postgresHoldStore } from "@jam-overture/loom/postgres"

import { db, store, treeId } from "../context/the-runtime--answering-a-held-change"

// page.mdx:49 — a program
const holds = postgresHoldStore(db)

const waiting = await holds.forTree(treeId)

// page.mdx:113 — a program
const page = await store.head(treeId)

const rows =
  waiting.ok && page.ok
    ? waiting.value.held.map((hold) => ({
        hold,
        stillAnswerable: hold.baseRevision === page.value.revision,
      }))
    : []

export { holds, waiting, page, rows, postgresHoldStore }
