/*
 * The block at page.mdx:49 of /docs/the-runtime/going-to-production, read on its own.
 *
 * It does the same job as the block above it, a different way, so it is a
 * program of its own rather than a continuation of the page's.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/the-runtime/going-to-production/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { postgresHoldStore, postgresTreeStore } from "@loom/runtime/postgres"
import { postgresTelemetryJournal } from "@loom/runtime/telemetry/postgres"

import { db } from "../context/the-runtime--going-to-production"

// page.mdx:49 — the same job as the block above, done differently
// A deployment.
const trees = postgresTreeStore(db)

const holds = postgresHoldStore(db)

const journal = postgresTelemetryJournal(db)

export { trees, holds, journal, postgresTreeStore, postgresHoldStore, postgresTelemetryJournal }
