/*
 * 4 code blocks from /docs/the-runtime/what-your-readers-do, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/the-runtime/what-your-readers-do/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { renderLoomTree } from "@loom/runtime/react"
import { broadcastReaderSignals } from "@loom/runtime/signals/broadcast"
import { useEffect, useRef } from "react"
import { parseReaderSignalBatch } from "@loom/runtime/signals"

import { registry, store, themes, tree } from "../context/the-runtime--what-your-readers-do"

// page.mdx:116 — a program
const rendered = renderLoomTree(tree, {
  resolver: registry,
  validator: registry,
  themes,
  addressed: true,
})

// page.mdx:135 — a program
"use client"

export const Measured = ({ children }: { readonly children: React.ReactNode }) => {
  const frame = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const root = frame.current?.querySelector("[data-loom-tree]")

    if (!(root instanceof Element)) return

    const started = broadcastReaderSignals(root, {
      kinds: ["dwelled", "activated"],
      types: { dwelled: ["loom.section"], activated: ["loom.link", "loom.action"] },
      send: (batch) => {
        navigator.sendBeacon("/api/signals", JSON.stringify(batch))
      },
    })

    if (!started.ok) {
      console.warn(started.error.detail)
      return
    }

    return started.value.stop
  }, [])

  return <div ref={frame}>{children}</div>
}

// page.mdx:207 — the inside of an object literal
const objectAtLine207 = {
kinds: ["viewed", "dwelled", "activated"],
types: {
  dwelled: ["loom.section", "loom.hero"],
  activated: ["loom.link", "loom.action"],
},
}

// page.mdx:238 — a program
export const POST = async (request: Request): Promise<Response> => {
  const read = parseReaderSignalBatch(await request.json())

  if (!read.ok) {
    return Response.json({ issues: read.error.issues }, { status: 400 })
  }

  await store(read.value)

  return new Response(null, { status: 204 })
}

export { rendered, objectAtLine207, renderLoomTree, broadcastReaderSignals, useEffect, useRef, parseReaderSignalBatch }
