/*
 * 2 code blocks from /docs/the-runtime/connecting-a-model, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/the-runtime/connecting-a-model/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import Anthropic from "@anthropic-ai/sdk"
import { modelInterpreter, randomIdFactory, systemClock } from "@loom/runtime"
import { anthropicModelClient } from "@loom/runtime/anthropic"
import { catalogueOf } from "@loom/runtime/sdk"

import { registry, themes } from "../context/the-runtime--connecting-a-model"
import type {
  EditIntent,
  InterpretationError,
  LoomTree,
  ProposedChange,
  Result,
} from "../context/the-runtime--connecting-a-model"

// page.mdx:27 — a program
type ChangeInterpreter = {
  interpret: (intent: EditIntent, tree: LoomTree) => Promise<Result<ProposedChange, InterpretationError>>
}

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

export const interpreter = modelInterpreter({
  client: anthropicModelClient(anthropic.messages),
  idFactory: randomIdFactory,
  clock: systemClock,
  catalogue: catalogueOf(registry),
  themeCatalogue: themes.catalogue(),
})

export { anthropic, Anthropic, modelInterpreter, randomIdFactory, systemClock, anthropicModelClient, catalogueOf }
export type { ChangeInterpreter }
