/*
 * 2 code blocks from /docs/the-runtime/what-a-render-reports, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/the-runtime/what-a-render-reports/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import {
  expect,
  options,
  renderLoomTree,
  rendered,
  tree,
} from "../context/the-runtime--what-a-render-reports"

// page.mdx:28 — a program
const { element, diagnostics } = renderLoomTree(tree, options)

// page.mdx:75 — the inside of a function
const functionAtLine75 = async () => {
expect(rendered.diagnostics).toEqual([])
}

export { element, diagnostics, functionAtLine75 }
