/*
 * 1 code block from /docs/the-runtime/the-history-of-a-page, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/the-runtime/the-history-of-a-page/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { memoryTreeStore } from "@jam-overture/loom/store"
import { postgresTreeStore } from "@jam-overture/loom/postgres"

import { db, holds, runtime } from "../context/the-runtime--the-history-of-a-page"

// page.mdx:155 — a program
const onThisSite = { store: memoryTreeStore(), holds, runtime }

const inADeployment = { store: postgresTreeStore(db), holds, runtime }

export { onThisSite, inADeployment, memoryTreeStore, postgresTreeStore }
