/*
 * 2 code blocks from /docs/the-runtime/what-every-ask-leaves-behind, read as one program.
 *
 * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the
 * page at app/(docs)/docs/the-runtime/what-every-ask-leaves-behind/page.mdx and run it again.
 *
 * Nothing imports this file. It exists so that the application's own
 * typechecker reads the code the site invites people to copy.
 */

import { commitIntent } from "@jam-overture/loom/write"
import { applyRetention, collectTelemetry } from "@jam-overture/loom/telemetry"
import { postgresTelemetryJournal } from "@jam-overture/loom/telemetry/postgres"

import {
  clock,
  db,
  holds,
  idFactory,
  intent,
  interpreter,
  journal,
  policySource,
  store,
} from "../context/the-runtime--what-every-ask-leaves-behind"

// page.mdx:61 — a program
const telemetry = collectTelemetry(postgresTelemetryJournal(db))

const runtime = { interpreter, policySource, clock, idFactory, events: telemetry.sink }

const outcome = await commitIntent({ store, holds, runtime }, intent)

await telemetry.flush()

// page.mdx:238 — a program
const pruned = await applyRetention(journal, { policy: { maxAgeMs: 30 * 24 * 60 * 60 * 1000 } })

export { telemetry, runtime, outcome, pruned, commitIntent, collectTelemetry, applyRetention, postgresTelemetryJournal }
