import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"
import { fileURLToPath } from "node:url"

import { pagesWithFences } from "./extract"
import { isCheckable } from "./model"
import { assemble, contextExportsIn } from "./program"

/**
 * The programs this site's pages add up to, as files on disk.
 *
 * There is a bespoke way to do this — extract the fences in a test, hand them to
 * the TypeScript compiler API, assert no diagnostics — and it would be worse.
 * It would check the snippets against a compiler configured *here*, in a second
 * place, whose settings could drift from the ones the application is actually
 * built with. What a reader wants to know is whether the code compiles under the
 * same strictness as the rest of the project: `strict`, `noUncheckedIndexedAccess`,
 * `exactOptionalPropertyTypes`, the lot.
 *
 * So the programs are written out as ordinary TypeScript files inside the
 * application, and `tsc --noEmit` — which `pnpm verify` already runs, twice —
 * checks them along with everything else. There is no second compiler and no
 * second configuration to keep true.
 *
 * The cost is a generated file in the repository, which is the same trade the
 * API reference already makes and for the same two reasons: a pull request that
 * changes a snippet shows the program that snippet became, and `compiled.test.ts`
 * regenerates and compares, so a page edited without regenerating is a red test
 * rather than a program describing last week's page.
 */

const here = fileURLToPath(new URL("./", import.meta.url))

export const COMPILED_DIR: string = join(here, "compiled")

export const CONTEXT_DIR: string = join(here, "context")

/** One file per page, named so the directory reads as a table of contents. */
export const compiledBaseName = (sectionSlug: string, pageSlug: string): string =>
  `${sectionSlug}--${pageSlug}`

const headerFor = (sectionSlug: string, pageSlug: string, count: number): string =>
  [
    "/*",
    ` * ${count} code ${count === 1 ? "block" : "blocks"} from /docs/${sectionSlug}/${pageSlug}, read as one program.`,
    " *",
    " * Generated by `pnpm --filter @loom/app docs:fences`. Do not edit: change the",
    ` * page at app/(docs)/docs/${sectionSlug}/${pageSlug}/page.mdx and run it again.`,
    " *",
    " * Nothing imports this file. It exists so that the application's own",
    " * typechecker reads the code the site invites people to copy.",
    " */",
  ].join("\n")

export type CompiledProgram = {
  readonly sectionSlug: string
  readonly pageSlug: string
  /** The file's name inside `compiled/`, extension included. */
  readonly fileName: string
  readonly source: string
  /** The page's context file, where it has one. */
  readonly contextFileName?: string
}

/**
 * A page's context file: the things its story assumes and its code never shows.
 *
 * Some pages are written from inside a request that has already happened — there
 * is a `request`, a `session`, a page loaded from a store. Those are the
 * narrator's, not the runtime's, and a program made only of the page's fences
 * cannot see them.
 *
 * The rule that keeps this from becoming a place to fake an API: a context file
 * may **name** what the story assumes, and must **import** anything the runtime
 * really provides. `context.test.ts` holds it to that by refusing any context
 * file that declares a name the runtime exports — so a snippet can never be made
 * to compile by inventing the function it calls.
 */
const contextFor = (sectionSlug: string, pageSlug: string): { path: string; fileName: string } | undefined => {
  const fileName = `${compiledBaseName(sectionSlug, pageSlug)}.ts`
  const path = join(CONTEXT_DIR, fileName)

  return existsSync(path) ? { path, fileName } : undefined
}

export const compiledPrograms = (): readonly CompiledProgram[] =>
  pagesWithFences().flatMap((page) => {
    const compiled = page.fences.filter(isCheckable)

    if (compiled.length === 0) return []

    const base = compiledBaseName(page.sectionSlug, page.pageSlug)
    const context = contextFor(page.sectionSlug, page.pageSlug)

    const assembly = assemble(
      page.fences,
      headerFor(page.sectionSlug, page.pageSlug, compiled.length),
      context === undefined
        ? undefined
        : {
            specifier: `../context/${base}`,
            exports: contextExportsIn(readFileSync(context.path, "utf8"), context.fileName),
          }
    )

    return [
      {
        sectionSlug: page.sectionSlug,
        pageSlug: page.pageSlug,
        fileName: `${base}.${assembly.extension}`,
        source: assembly.source,
        ...(context === undefined ? {} : { contextFileName: context.fileName }),
      },
    ]
  })
