import { createElement, type ReactElement } from "react"

/**
 * The one stylesheet this library emits, and the reason there is one at all.
 *
 * Every other value a primitive uses is an inline style, which is what keeps a
 * render a pure function of the tree with nothing to attach and nothing to load.
 * Five things cannot be said inline, and the first three are the difference
 * between a primitive that looks like a UI kit and one that looks like a
 * product:
 *
 * - **keyframes** — an entrance, a drift, a marquee
 * - **state selectors** — `:hover`, `:focus-visible`, `details[open]`,
 *   `[aria-current="page"]`. The last one is a state the *tree* sets rather
 *   than the reader, and it is here for the same reason as the others: a link
 *   that says which page you are on has to be marked with the mark hovering
 *   already makes, and one element cannot hold two values of one property.
 * - **`prefers-reduced-motion`** — the one media query that is not a layout
 *   decision, and honouring it is not optional
 * - **pseudo-elements** — `::after`. A card whose title anchor covers the whole
 *   surface is one overlay generated by that anchor; the alternative is a
 *   second element in the markup that exists only to be clicked.
 * - **position selectors** — `:last-child`, `:first-of-type`. A render is a
 *   pure function of one node, so no primitive can know it is the last of its
 *   siblings; a rail that must stop at the final dot, or a grid that runs its
 *   lead piece across the top, has nowhere else to be said.
 *
 * That last one is ordinary CSS doing what only CSS can, and it needs no more
 * justification than `:hover` does — where a primitive sits among its siblings
 * is the browser's business, and how a primitive is styled is simply part of
 * what that primitive *is*. Two mechanics are worth knowing before writing one,
 * though, because both are easy to get wrong once and hard to see afterwards:
 *
 * 1. **An inline style beats a rule here**, always. A primitive that sets a
 *    property inline has made that property unreachable from this file, so a
 *    value the stylesheet needs to vary — `loom.milestone`'s bottom gap — must
 *    not also be set on the element.
 * 2. **Scope every selector to a library class.** `li:last-child` would reach
 *    every list on the host's page; `.loom-rail > li:last-child` reaches only
 *    the one this library drew.
 *
 * So a primitive that needs any of them emits this element beside its own root.
 * It is static text: no prop reaches it, nothing is interpolated into it, and it
 * is byte-identical under every theme because every value in it is a `var()`.
 * That matters more than it looks — it is what keeps 0049's re-theme guarantee
 * true for animated primitives, and it is why an AI proposal cannot reach the
 * animation. The tree configures content, variant and theme; motion is part of
 * the implementation the registry vouches for, which is the bargain in 0007
 * working exactly as intended.
 *
 * React 19 dedupes and hoists a `<style>` carrying `href` and `precedence`, so
 * twenty animated primitives on one page emit one stylesheet in the document
 * head. A renderer that does not hoist emits identical copies, which are inert.
 */

export const STYLESHEET_HREF = "loom-primitives"
export const STYLESHEET_PRECEDENCE = "loom"

/** Class names the library's primitives apply. Exported so a test can name them. */
export const LIBRARY_CLASS = {
  /** Fades and lifts into place once, on entry. Stagger with `animationDelay`. */
  rise: "loom-rise",
  /** Raises a card on hover, and marks it as a surface that responds. */
  lift: "loom-lift",
  /** Wipes an underline in from the left on hover — a link that is a whole tile. */
  underline: "loom-underline",
  /** Two slow-drifting colour fields, for a hero backdrop that is not a flat wash. */
  aurora: "loom-aurora",
  /** The disclosure marker of a `details`, rotated when its section is open. */
  marker: "loom-marker",
  /** A logo held back to grey until it is pointed at. */
  mark: "loom-mark",
  /** A `loom.milestone-list`: spaces its entries and ends its own rail. */
  rail: "loom-rail",
  /** The same list, set tighter — a changelog to scan rather than a history to read. */
  railTight: "loom-rail-tight",
  /** The same list with the connecting line dropped, dots kept. */
  railNone: "loom-rail-none",
  /** One entry's connector, hidden on the last entry because only CSS knows which that is. */
  railLine: "loom-rail-line",
  /** One entry's content cell, which carries the gap to the entry below it. */
  railBody: "loom-rail-body",
  /** A card whose title anchor is stretched over the whole surface. */
  cover: "loom-cover",
  /** That anchor. Its `::after` is what makes the surface clickable. */
  coverLink: "loom-cover-link",
  /** A card's cover image, cropped to a ratio the card owns rather than the file does. */
  coverMedia: "loom-cover-media",
  /** A card's padded interior, so a lead layout can set it beside the cover. */
  coverBody: "loom-cover-body",
  /** A `loom.article-grid` running its first piece across the top. */
  lead: "loom-lead",
  /** One `loom.field`. Named so the form it sits in can size it in a row. */
  field: "loom-field",
  /** Any control inside a field: the focus ring, the hover, the placeholder. */
  input: "loom-input",
  /** The wrapper that draws a select's chevron, since the native one is not the palette's. */
  select: "loom-select",
  /** A `loom.form` laid out as a single row — see the rule about sizing children. */
  formInline: "loom-form-inline",
  /**
   * A `loom.avatar-row` cluster: each face overlaps the one before it and rings
   * itself in the page's ground so the edge reads. The ring is `bg-canvas`
   * because a primitive cannot know what it is sitting on — a cluster placed
   * inside a `loom.card` rings itself in the canvas colour rather than the
   * card's, which is a hair off and the honest limit of a static stylesheet.
   */
  cluster: "loom-cluster",
  /** A `loom.comparison-table`'s `<table>`: separators, padding, and the featured column. */
  compare: "loom-compare",
  /** The same table set as a spec to scan rather than a page to read. */
  compareTight: "loom-compare-tight",
  /** One `loom.comparison-row`, so the whole row can answer a pointer. */
  compareRow: "loom-compare-row",
  /** Its leading cell — the criterion, which stays put while the band scrolls. */
  compareKey: "loom-compare-key",
  /** A qualifier under an answer, dimmed — and re-lit where the column is tinted. */
  compareNote: "loom-compare-note",
  /**
   * The three verdicts. Their colour is here rather than on the element because
   * a tinted column re-inks the two that recede — `fg-subtle` on `accent-subtle`
   * measures 3.76:1 across the registered palettes, under the bar 0074 holds a
   * text slot to — and an inline colour would beat the rule that does it.
   */
  compareYes: "loom-compare-yes",
  compareNo: "loom-compare-no",
  comparePartial: "loom-compare-partial",
  /**
   * The subject column a page is steering towards, by position. A column is
   * not a node (0084), so this is the only handle it has — and four of them,
   * because each is a static rule rather than an interpolated index.
   */
  compareFeatureFirst: "loom-compare-feature-1",
  compareFeatureSecond: "loom-compare-feature-2",
  compareFeatureThird: "loom-compare-feature-3",
  compareFeatureFourth: "loom-compare-feature-4",
  /** A `loom.mosaic`: one column until there is room for six. */
  mosaic: "loom-mosaic",
  /** Its three rhythms, each a cycle of spans that fills a six-column row exactly. */
  mosaicAlternating: "loom-mosaic-alternating",
  mosaicShowcase: "loom-mosaic-showcase",
  mosaicLead: "loom-mosaic-lead",
} as const

/**
 * Reduced motion removes movement, never feedback: a `.loom-rise` element ends
 * at `opacity: 1` rather than never arriving, and hover still recolours. An
 * entrance animation that is simply switched off is how a page renders blank
 * for anyone who asked their system to calm it down.
 */
const CSS = `
@keyframes loom-rise {
  from { opacity: 0; transform: translate3d(0, 0.9rem, 0); }
  to { opacity: 1; transform: none; }
}
@keyframes loom-aurora {
  0% { transform: translate3d(-6%, -4%, 0) scale(1); }
  50% { transform: translate3d(6%, 4%, 0) scale(1.25); }
  100% { transform: translate3d(-6%, -4%, 0) scale(1); }
}
.loom-rise {
  animation: loom-rise calc(var(--loom-motion-slow) * 1.6) cubic-bezier(0.22, 1, 0.36, 1) both;
}
.loom-lift {
  transition: transform var(--loom-motion-medium) ease, box-shadow var(--loom-motion-medium) ease, border-color var(--loom-motion-medium) ease;
}
.loom-lift:hover {
  transform: translate3d(0, -4px, 0);
  box-shadow: 0 24px 48px -34px var(--loom-fg-default);
  border-color: var(--loom-border-accent);
}
.loom-underline {
  background-image: linear-gradient(var(--loom-accent), var(--loom-accent));
  background-repeat: no-repeat;
  background-position: 0 100%;
  background-size: 0% 2px;
  transition: background-size var(--loom-motion-medium) cubic-bezier(0.22, 1, 0.36, 1);
}
.loom-underline:hover, .loom-underline:focus-visible {
  background-size: 100% 2px;
}
.loom-underline[aria-current="page"] {
  background-size: 100% 2px;
}
.loom-aurora {
  animation: loom-aurora calc(var(--loom-motion-slow) * 40) ease-in-out infinite;
}
.loom-marker {
  transition: transform var(--loom-motion-medium) cubic-bezier(0.22, 1, 0.36, 1);
}
details[open] > summary .loom-marker {
  transform: rotate(45deg);
}
.loom-mark {
  filter: grayscale(1);
  opacity: 0.72;
  transition: filter var(--loom-motion-medium) ease, opacity var(--loom-motion-medium) ease;
}
.loom-mark:hover, a:hover > .loom-mark, a:focus-visible > .loom-mark {
  filter: none;
  opacity: 1;
}
.loom-rail > li .loom-rail-body {
  padding-block-end: var(--loom-spacing-5);
}
.loom-rail-tight > li .loom-rail-body {
  padding-block-end: var(--loom-spacing-3);
}
.loom-rail > li:last-child .loom-rail-body {
  padding-block-end: 0;
}
.loom-rail > li:last-child .loom-rail-line, .loom-rail-none .loom-rail-line {
  visibility: hidden;
}
.loom-cover {
  position: relative;
  flex-direction: column;
}
.loom-cover > .loom-cover-body {
  flex: 1 1 auto;
}
.loom-cover-link::after {
  content: "";
  position: absolute;
  inset: 0;
}
.loom-cover-media {
  aspect-ratio: 16 / 10;
  overflow: hidden;
}
.loom-lead > article:first-of-type {
  grid-column: 1 / -1;
  flex-direction: row;
  flex-wrap: wrap;
}
.loom-lead > article:first-of-type > .loom-cover-media,
.loom-lead > article:first-of-type > .loom-cover-body {
  flex: 1 1 20rem;
}
.loom-lead > article:first-of-type > .loom-cover-media {
  aspect-ratio: auto;
  min-height: 16rem;
}
.loom-input {
  transition: border-color var(--loom-motion-medium) ease;
}
.loom-input:hover {
  border-color: var(--loom-border-strong);
}
.loom-input:focus-visible {
  outline: 2px solid var(--loom-border-accent);
  outline-offset: 2px;
  border-color: var(--loom-border-accent);
}
.loom-input::placeholder {
  color: var(--loom-fg-muted);
  opacity: 1;
}
.loom-input:disabled {
  cursor: not-allowed;
}
.loom-select::after {
  content: "";
  position: absolute;
  inset-inline-end: var(--loom-spacing-3);
  inset-block-start: 50%;
  width: 0.42em;
  height: 0.42em;
  border-inline-end: 2px solid currentColor;
  border-block-end: 2px solid currentColor;
  transform: translate3d(0, -70%, 0) rotate(45deg);
  color: var(--loom-fg-muted);
  pointer-events: none;
}
.loom-form-inline > .loom-field {
  flex: 1 1 14rem;
}
.loom-cluster > * + * {
  margin-inline-start: -0.7em;
}
.loom-cluster > * {
  box-shadow: 0 0 0 2px var(--loom-bg-canvas);
}
.loom-compare th, .loom-compare td {
  padding: var(--loom-spacing-3) var(--loom-spacing-4);
}
.loom-compare-tight th, .loom-compare-tight td {
  padding: var(--loom-spacing-2) var(--loom-spacing-3);
}
.loom-compare thead > tr > * {
  border-block-end: 1px solid var(--loom-border-strong);
}
.loom-compare tbody > tr + tr > * {
  border-block-start: 1px solid var(--loom-border-subtle);
}
.loom-compare-key {
  position: sticky;
  inset-inline-start: 0;
  background: var(--loom-bg-surface);
  z-index: 1;
}
.loom-compare-row > * {
  transition: background-color var(--loom-motion-medium) ease;
}
.loom-compare-row:hover > * {
  background: var(--loom-bg-surface-muted);
}
.loom-compare-note, .loom-compare-no {
  color: var(--loom-fg-subtle);
}
.loom-compare-yes {
  color: var(--loom-accent-strong);
}
.loom-compare-partial {
  color: var(--loom-fg-muted);
}
.loom-compare-feature-1 tr > *:nth-child(2),
.loom-compare-feature-2 tr > *:nth-child(3),
.loom-compare-feature-3 tr > *:nth-child(4),
.loom-compare-feature-4 tr > *:nth-child(5) {
  background: var(--loom-accent-subtle);
  border-inline: 1px solid var(--loom-border-accent);
}
.loom-compare-feature-1 tr > *:nth-child(2) .loom-compare-note,
.loom-compare-feature-2 tr > *:nth-child(3) .loom-compare-note,
.loom-compare-feature-3 tr > *:nth-child(4) .loom-compare-note,
.loom-compare-feature-4 tr > *:nth-child(5) .loom-compare-note,
.loom-compare-feature-1 tr > *:nth-child(2) .loom-compare-no,
.loom-compare-feature-2 tr > *:nth-child(3) .loom-compare-no,
.loom-compare-feature-3 tr > *:nth-child(4) .loom-compare-no,
.loom-compare-feature-4 tr > *:nth-child(5) .loom-compare-no {
  color: var(--loom-fg-muted);
}
.loom-mosaic {
  display: grid;
  grid-template-columns: 1fr;
  align-items: stretch;
}
@media (min-width: 48rem) {
  .loom-mosaic {
    grid-template-columns: repeat(6, 1fr);
  }
  .loom-mosaic-alternating > *:nth-child(4n + 1),
  .loom-mosaic-alternating > *:nth-child(4n) {
    grid-column: span 4;
  }
  .loom-mosaic-alternating > *:nth-child(4n + 2),
  .loom-mosaic-alternating > *:nth-child(4n + 3) {
    grid-column: span 2;
  }
  .loom-mosaic-showcase > *:nth-child(5n + 1),
  .loom-mosaic-showcase > *:nth-child(5n + 2) {
    grid-column: span 3;
  }
  .loom-mosaic-showcase > *:nth-child(5n + 3),
  .loom-mosaic-showcase > *:nth-child(5n + 4),
  .loom-mosaic-showcase > *:nth-child(5n) {
    grid-column: span 2;
  }
  .loom-mosaic-lead > * {
    grid-column: span 2;
  }
  .loom-mosaic-lead > *:first-child {
    grid-column: span 6;
  }
}
@media (prefers-reduced-motion: reduce) {
  .loom-rise, .loom-aurora {
    animation: none;
    opacity: 1;
    transform: none;
  }
  .loom-lift, .loom-underline, .loom-marker, .loom-mark, .loom-input, .loom-compare-row > * {
    transition: none;
  }
  .loom-lift:hover {
    transform: none;
  }
}
`.trim()

/**
 * Emitted beside a primitive's own root element rather than around it, for the
 * reason `editable.ts` gives for never wrapping: a wrapper changes what `>`,
 * `:first-child` and `:nth-child` select. A hoisted `<style>` is removed from
 * the flow entirely, and an un-hoisted one is a metadata element siblings do
 * not count.
 */
export const libraryStylesheet = (): ReactElement =>
  createElement("style", {
    href: STYLESHEET_HREF,
    precedence: STYLESHEET_PRECEDENCE,
    children: CSS,
  })
