import { createElement, type ReactElement } from "react"

/**
 * The one stylesheet this library emits, and the reason there is one at all.
 *
 * Every other value a primitive uses is an inline style, which is what keeps a
 * render a pure function of the tree with nothing to attach and nothing to load.
 * Five things cannot be said inline, and the first three are the difference
 * between a primitive that looks like a UI kit and one that looks like a
 * product:
 *
 * - **keyframes** — an entrance, a drift, a marquee
 * - **state selectors** — `:hover`, `:focus-visible`, `details[open]`,
 *   `[aria-current="page"]`. The last one is a state the *tree* sets rather
 *   than the reader, and it is here for the same reason as the others: a link
 *   that says which page you are on has to be marked with the mark hovering
 *   already makes, and one element cannot hold two values of one property.
 * - **`prefers-reduced-motion`** — the one media query that is not a layout
 *   decision, and honouring it is not optional
 * - **pseudo-elements** — `::after`. A card whose title anchor covers the whole
 *   surface is one overlay generated by that anchor; the alternative is a
 *   second element in the markup that exists only to be clicked.
 * - **position selectors** — `:last-child`, `:first-of-type`. A render is a
 *   pure function of one node, so no primitive can know it is the last of its
 *   siblings; a rail that must stop at the final dot, or a grid that runs its
 *   lead piece across the top, has nowhere else to be said.
 *
 * That last one is ordinary CSS doing what only CSS can, and it needs no more
 * justification than `:hover` does — where a primitive sits among its siblings
 * is the browser's business, and how a primitive is styled is simply part of
 * what that primitive *is*. Two mechanics are worth knowing before writing one,
 * though, because all three are easy to get wrong once and hard to see
 * afterwards:
 *
 * 1. **An inline style beats a rule here**, always. A primitive that sets a
 *    property inline has made that property unreachable from this file, so a
 *    value the stylesheet needs to vary — `loom.milestone`'s bottom gap — must
 *    not also be set on the element.
 * 2. **Scope every selector to a library class.** `li:last-child` would reach
 *    every list on the host's page; `.loom-rail > li:last-child` reaches only
 *    the one this library drew.
 * 3. **A missing `}` deletes the rule after it, silently.** This is a template
 *    literal rather than a parsed stylesheet, so nothing here or in a test
 *    noticed when the comparison band's last rule shipped unclosed on 22 August
 *    and swallowed `.loom-list { margin: 0 }` whole — CSS error recovery treats
 *    the next rule as one bad declaration, drops it, and carries on rendering
 *    everything else correctly. Every list in the library carried the browser's
 *    default margins for a day and no assertion could see it. `library.test.ts`
 *    now parses this text and holds every block closed; do not weaken that test
 *    to add a rule it complains about.
 *
 * So a primitive that needs any of them emits this element beside its own root.
 * It is static text: no prop reaches it, nothing is interpolated into it, and it
 * is byte-identical under every theme because every value in it is a `var()`.
 * That matters more than it looks — it is what keeps 0049's re-theme guarantee
 * true for animated primitives, and it is why an AI proposal cannot reach the
 * animation. The tree configures content, variant and theme; motion is part of
 * the implementation the registry vouches for, which is the bargain in 0007
 * working exactly as intended.
 *
 * React 19 dedupes and hoists a `<style>` carrying `href` and `precedence`, so
 * twenty animated primitives on one page emit one stylesheet in the document
 * head. A renderer that does not hoist emits identical copies, which are inert.
 */

export const STYLESHEET_HREF = "loom-primitives"
export const STYLESHEET_PRECEDENCE = "loom"

/**
 * The space a `loom.marquee` puts between its items, declared by the primitive
 * and applied by the rules below.
 *
 * It is a custom property rather than an inline `gap` because the *same* value
 * is wanted in two places that need different conditions: between the items
 * always, and after the last one **only while the run is tiling against its
 * own echo**. An inline declaration can express the first and cannot express
 * the second, which is 0155 — and the cost of getting it wrong was measured,
 * in `loom.marquee`'s own doc comment, at eight pixels and one whole column.
 */
export const MARQUEE_GAP = "--loom-marquee-gap"

/** Class names the library's primitives apply. Exported so a test can name them. */
export const LIBRARY_CLASS = {
  /** Fades and lifts into place once, on entry. Stagger with `animationDelay`. */
  rise: "loom-rise",
  /** Raises a card on hover, and marks it as a surface that responds. */
  lift: "loom-lift",
  /** Wipes an underline in from the left on hover — a link that is a whole tile. */
  underline: "loom-underline",
  /** Two slow-drifting colour fields, for a hero backdrop that is not a flat wash. */
  aurora: "loom-aurora",
  /** The disclosure marker of a `details`, rotated when its section is open. */
  marker: "loom-marker",
  /** A logo held back to grey until it is pointed at. */
  mark: "loom-mark",
  /** A `loom.milestone-list`: spaces its entries, ends its rail, sizes its marker column. */
  rail: "loom-rail",
  /** The same list, set tighter — a changelog to scan rather than a history to read. */
  railTight: "loom-rail-tight",
  /** The same list with the connecting line dropped, dots kept. */
  railNone: "loom-rail-none",
  /**
   * One `loom.milestone`, and the reason its own layout is here rather than on
   * the element: **a child that lays itself out inline cannot be rearranged by
   * the container it is in.** An inline style beats a rule, so the marker
   * column, the rail's direction and the dot's optical offset were all
   * unreachable from any parent — and a second arrangement of the same content
   * model is exactly what the naming rule — a container is its child's name
   * plus the arrangement — says a second container is for. Moving four
   * declarations into this file is what let `loom.milestone-row` exist without
   * a second child type that renders the same three fields.
   *
   * It stays on the *entry* rather than on the list, which is the property the
   * inline version was protecting: a milestone that finds itself outside a
   * list still lays itself out, because the class travels with the child.
   */
  milestone: "loom-milestone",
  /** Its marker cell — right-aligned on a rail, above the title in a row. */
  railMarker: "loom-rail-marker",
  /** Its dot-and-line cell, which runs down the page on a rail and across it in a row. */
  railTrack: "loom-rail-track",
  /** The dot itself, offset onto the marker's first line where the marker is beside it. */
  railDot: "loom-rail-dot",
  /** One entry's connector, hidden on the last entry because only CSS knows which that is. */
  railLine: "loom-rail-line",
  /** One entry's content cell, which carries the gap to the entry below it. */
  railBody: "loom-rail-body",
  /** A `loom.milestone-row`: the same entries laid across, as a process band. */
  milestoneRow: "loom-milestone-row",
  /**
   * A `loom.embed` frame whose shape follows its own width — portrait while it
   * is narrow, 16/10 once it is not. The one shape that cannot be an inline
   * `aspect-ratio`, because there is no single ratio to write down.
   */
  frameAdaptive: "loom-frame-adaptive",
  /** A card whose title anchor is stretched over the whole surface. */
  cover: "loom-cover",
  /** That anchor. Its `::after` is what makes the surface clickable. */
  coverLink: "loom-cover-link",
  /** A card's cover image, cropped to a ratio the card owns rather than the file does. */
  coverMedia: "loom-cover-media",
  /** A card's padded interior, so a lead layout can set it beside the cover. */
  coverBody: "loom-cover-body",
  /** A `loom.article-grid` running its first piece across the top. */
  lead: "loom-lead",
  /** One `loom.field`. Named so the form it sits in can size it in a row. */
  field: "loom-field",
  /** Any control inside a field: the focus ring, the hover, the placeholder. */
  input: "loom-input",
  /** The wrapper that draws a select's chevron, since the native one is not the palette's. */
  select: "loom-select",
  /** A `loom.form` laid out as a single row — see the rule about sizing children. */
  formInline: "loom-form-inline",
  /**
   * A `loom.avatar-row` cluster: each face overlaps the one before it and rings
   * itself in the page's ground so the edge reads. The ring is `bg-canvas`
   * because a primitive cannot know what it is sitting on — a cluster placed
   * inside a `loom.card` rings itself in the canvas colour rather than the
   * card's, which is a hair off and the honest limit of a static stylesheet.
   */
  cluster: "loom-cluster",
  /**
   * The region a band too wide for the screen scrolls inside — `loom.table`'s
   * and `loom.comparison-table`'s, which had one each and neither had anything
   * but `overflow-x`.
   *
   * It is a class rather than the inline pair it replaces because three of the
   * four things a scroller needs cannot be said on the element: the snap
   * positions belong to the children, the focus ring is a state selector, and
   * the scrollbar is the browser's own furniture. `loom.carousel` worked all of
   * this out on 28 August and the only thing added here is
   * `scroll-padding-inline-start`, which a carousel has no use for and a table
   * with a column that stays put cannot do without.
   */
  scrollX: "loom-scroll-x",
  /**
   * The comparison band's scroller, which differs from the general table's in
   * one line: it holds its criterion column in place, so a snap has to land a
   * subject *beside* that column rather than behind it.
   */
  compareScroll: "loom-compare-scroll",
  /** A `loom.comparison-table`'s `<table>`: separators, padding, and the featured column. */
  compare: "loom-compare",
  /** The same table set as a spec to scan rather than a page to read. */
  compareTight: "loom-compare-tight",
  /** One `loom.comparison-row`, so the whole row can answer a pointer. */
  compareRow: "loom-compare-row",
  /** Its leading cell — the criterion, which stays put while the band scrolls. */
  compareKey: "loom-compare-key",
  /** A qualifier under an answer, dimmed — and re-lit where the column is tinted. */
  compareNote: "loom-compare-note",
  /**
   * The three verdicts. Their colour is here rather than on the element because
   * a tinted column re-inks the two that recede — `fg-subtle` on `accent-subtle`
   * measures 3.76:1 across the registered palettes, under the bar a palette
   * slot carrying text is held to — and an inline colour would beat the rule that does it.
   */
  compareYes: "loom-compare-yes",
  compareNo: "loom-compare-no",
  comparePartial: "loom-compare-partial",
  /**
   * The subject column a page is steering towards, by position. A column is
   * not a node — in a two-dimensional band rows are nodes and columns are
   * positions — so this is the only handle it has — and four of them,
   * because each is a static rule rather than an interpolated index.
   */
  compareFeatureFirst: "loom-compare-feature-1",
  compareFeatureSecond: "loom-compare-feature-2",
  compareFeatureThird: "loom-compare-feature-3",
  compareFeatureFourth: "loom-compare-feature-4",
  /**
   * A `loom.list`: its markers take the accent, and its rows carry the gap
   * between them. Both are here rather than inline because neither is
   * expressible on the element that needs it — `::marker` is a pseudo-element,
   * and a row's gap is a fact about the *list* that only the row can apply.
   */
  list: "loom-list",
  /** The same list set tight — points to scan rather than points to read. */
  listTight: "loom-list-tight",
  /** The same list set loose, for rows that are a sentence each. */
  listLoose: "loom-list-loose",
  /**
   * A `loom.table`: the padding its cells share, and the rules between its
   * rows. Both are the *table's* decisions applied to cells it does not render,
   * which is the one thing an inline style cannot reach.
   */
  table: "loom-table",
  /** The same table drawn as a bordered surface, which is what makes its heading column stick. */
  tablePanel: "loom-table-panel",
  /** The same table set tight — a spec to scan — and set loose, a page to read. */
  tableTight: "loom-table-tight",
  tableLoose: "loom-table-loose",
  /** Vertical rules as well as horizontal ones, and no rules at all. */
  tableGrid: "loom-table-grid",
  tableFlush: "loom-table-flush",
  /**
   * A table whose cells hold sentences rather than values, which is the one
   * thing about a table's *content* that changes what its narrow rendering
   * should be and the one thing no rule here can see.
   *
   * It gives the body cells a readable measure below the width where a phone
   * starts squeezing them, so the band overflows and scrolls instead of
   * crushing three sentences into a hundred pixels each. It is switched by a
   * prop because it had to be: measured in Chromium, `min-inline-size:
   * fit-content(10rem)` — which is exactly this rule conditioned on the
   * content, and would have needed no prop at all — is ignored outright, and an
   * unconditional minimum takes a four-column table of figures from 350px to
   * 744px and makes *it* scroll. The numbers are in the 15 September report.
   */
  tableProse: "loom-table-prose",
  /** One `loom.table-row`, so the whole row can answer a pointer. */
  tableRow: "loom-table-row",
  /** A row the page is pointing at, which keeps its tint under that pointer. */
  tableHighlight: "loom-table-highlight",
  /** A `loom.table-cell` heading a row, which stays put while a panel scrolls. */
  tableKey: "loom-table-key",
  /**
   * A `loom.marquee`. The band that clips; the track that travels; the run of
   * items; the second, decorative run that makes the loop seamless; the
   * direction, the edge fade, and the still rendering the band takes while
   * somebody is editing it.
   *
   * Everything about the track is here rather than on the element, and that is
   * load-bearing rather than tidy: its duration is chosen by how many items the
   * run holds, its width and its animation are cancelled by the still variant
   * and again by reduced motion, and an inline style would beat all three.
   */
  marquee: "loom-marquee",
  marqueeTrack: "loom-marquee-track",
  marqueeRun: "loom-marquee-run",
  marqueeEcho: "loom-marquee-echo",
  marqueeReverse: "loom-marquee-reverse",
  marqueeFaded: "loom-marquee-faded",
  marqueeStill: "loom-marquee-still",
  /**
   * A `loom.offering`. The card declares the containment; the frame inside it
   * is what the `@container` rule flips from a column into a row, because a
   * container query reads its *ancestor* and never the element that declared it.
   *
   * Everything about the frame's direction, the body's growth and the action's
   * `auto` start margin is here rather than on the element, and that is
   * load-bearing rather than tidy: the row layout cancels the margin, and an
   * inline style would beat the rule that does it.
   */
  offering: "loom-offering",
  offeringFrame: "loom-offering-frame",
  offeringBody: "loom-offering-body",
  offeringAction: "loom-offering-action",
  /** A `loom.credential`: the positioned ancestor its stretched name anchor needs. */
  credential: "loom-credential",
  /**
   * A `loom.recording`. The card, the frame the `@container` rule flips, the
   * artwork panel, the body beside it, the play mark over the artwork and the
   * runtime pinned into its corner.
   *
   * The frame's direction is here for `loom-offering-frame`'s reason — an
   * inline value would beat the rule that flips it — and the play mark's
   * position is here because it is a `transform` the hover state has to
   * *extend* rather than replace. A mark centred by an inline
   * `translate(-50%, -50%)` and scaled by a rule would lose the centring the
   * moment the rule fired, which is the kind of defect that only shows on
   * hover and therefore never in a screenshot.
   */
  recording: "loom-recording",
  recordingFrame: "loom-recording-frame",
  recordingArt: "loom-recording-art",
  recordingBody: "loom-recording-body",
  recordingPlay: "loom-recording-play",
  recordingTime: "loom-recording-time",
  /**
   * A `loom.event`. The card, the frame, the date in its margin, the body and
   * the action pinned to the card's end.
   *
   * The rule between the date and the rest is on `loom-event-when` and only
   * inside the `@container` block, because it is an inline-end border in the
   * row arrangement and would be a horizontal line under a date — a divider
   * between nothing — in the stacked one.
   */
  event: "loom-event",
  eventFrame: "loom-event-frame",
  eventWhen: "loom-event-when",
  eventBody: "loom-event-body",
  eventAction: "loom-event-action",
  /**
   * A `loom.nav`. The bar itself, the box holding its disclosure control, and
   * the menu that control opens and closes.
   *
   * The menu's `display` is here rather than on the element, and that is the
   * whole reason the disclosure works at all: the disclosure contract — the control
   * owns its button and the primitive owns the region — is a rule that hides
   * the region, and an inline `display: flex` would beat it. Its
   * alignment stays inline, because that varies by prop and nothing needs to
   * override it.
   *
   * The drawer aligns its items to `flex-start` rather than stretching them,
   * and that is a rendering decision rather than a tidiness one: the current
   * item is marked by an underline the link paints across its own box, so a
   * stretched row draws that rule the full width of the bar. One mark that
   * renders as a text underline on a laptop and as a full-width rule on a
   * phone is the same primitive saying two different things.
   */
  nav: "loom-nav",
  navToggle: "loom-nav-toggle",
  navMenu: "loom-nav-menu",
  /** Its actions end, which takes the slack on a phone when no control was built. */
  navActions: "loom-nav-actions",
  /**
   * The three primitives that present a region, and the regions they present.
   *
   * Each root carries `data-loom-presented` — written there by the control the
   * primitive placed inside it — and each region is hidden by a rule keyed on
   * that root. **The rule hides on `"false"` and never reveals on `"true"`**, so
   * a page served without scripting has no control, no attribute, no rule that
   * matches, and the region simply there; `presentation.ts` carries why that
   * direction is the only safe one and `presentation.test.ts` asserts it.
   *
   * The regions' own `display` is here rather than on the element for the first
   * mechanic above: an inline value beats a rule, so a panel that declared its
   * own `display` would be a panel the hide rule silently failed to hide.
   */
  popover: "loom-popover",
  popoverPanel: "loom-popover-panel",
  menu: "loom-menu",
  /**
   * A menu's dropped panel, and the rows inside it.
   *
   * The rows are a rule on the panel's **direct children** rather than a style
   * on a child this library would have to own, which is `loom.link-pager`'s
   * pattern a second time and works for the same reason: `loom.link` leaves its
   * padding off the element deliberately, so a container is free to give it a
   * hit area. It reaches a `loom.action` in the last row of an account menu
   * without either of them knowing about the other.
   */
  menuPanel: "loom-menu-panel",
  /**
   * A `loom.lightbox`: the root the state is published on, the tile on the page,
   * the region drawn over the viewport, and the plate inside it.
   *
   * The root is also where the **present** control is positioned from, and that
   * is not a convenience. A control paints itself with an inline `style`
   * (`control.ts`), so the class the runtime stamps on it is the only handle a
   * primitive has — and the chip belongs over the corner of the tile, which is a
   * `position` no control sets for itself.
   */
  lightbox: "loom-lightbox",
  lightboxPreview: "loom-lightbox-preview",
  lightboxFrame: "loom-lightbox-frame",
  lightboxPanel: "loom-lightbox-panel",
  /**
   * A `loom.before-after`, which carried no class at all until it took a
   * control. Same reason as the lightbox's root: the slider is the runtime's
   * element and where it sits over the band is this primitive's decision.
   */
  beforeAfter: "loom-before-after",
  /**
   * A `loom.feature`. The tile, which measures itself; the box holding its two
   * halves; the words; and the region it places what it was handed in.
   *
   * `featureFigured` is on the frame of a tile that was handed something, and
   * it is the only thing the `@container` rule looks at — a tile with nothing
   * in its `media` region is a column at every width, which is what every
   * feature in this library was before the region existed and what most of
   * them still are.
   */
  feature: "loom-feature",
  featureFrame: "loom-feature-frame",
  featureFigured: "loom-feature-figured",
  featureCopy: "loom-feature-copy",
  featureMedia: "loom-feature-media",
  /** A `loom.mosaic`: one column until the band itself has room for six. */
  mosaic: "loom-mosaic",
  /** Its three rhythms, each a cycle of spans that fills a six-column row exactly. */
  mosaicAlternating: "loom-mosaic-alternating",
  mosaicShowcase: "loom-mosaic-showcase",
  mosaicLead: "loom-mosaic-lead",
  /**
   * A `loom.orbit`. The square stage; the dashed guides nothing sits on; the
   * layer that turns; one seat on it; the item in that seat, which turns the
   * other way at the same rate so a wordmark stays the right way up.
   *
   * The two animations are one duration written twice and they have to stay
   * equal — a counter-rotation that runs at a different rate is a logo that
   * tumbles slowly instead of staying upright — so both read the same
   * multiple of `--loom-motion-slow` and neither is expressible inline.
   */
  orbit: "loom-orbit",
  orbitGuide: "loom-orbit-guide",
  /** A seat or a guide on the second ring, which is the one a narrow band opens out. */
  orbitInner: "loom-orbit-inner",
  orbitSpinner: "loom-orbit-spinner",
  orbitSeat: "loom-orbit-seat",
  orbitItem: "loom-orbit-item",
  /** The ring turning the other way, and the still rendering it takes while somebody edits it. */
  /**
   * The ring drawn with a connector from each seat back to the middle. It is on
   * the stage rather than on a seat, because what it turns on is one prop of
   * the arrangement and a seat knows nothing about the arrangement.
   */
  orbitSpoked: "loom-orbit-spoked",
  orbitReverse: "loom-orbit-reverse",
  orbitStill: "loom-orbit-still",
  /**
   * A `loom.message`. The turn itself and the column holding its attribution
   * above its bubble, plus the two sides that are not the base rendering.
   *
   * **Its layout is here and not on the element**, which is `loom.milestone`'s
   * lesson applied before it costs anything rather than after: an inline
   * `flex-direction` on a turn would pin these into bubbles forever, and the
   * second arrangement of a conversation — a transcript set flush left, the way
   * a published interview reads — is a container the same naming rule says to write
   * when somebody wants one. What stays inline is the paint, which no arrangement
   * varies.
   *
   * **The face aligns with the name, not with the foot of the bubble.** This
   * row was `align-items: flex-end` from the day it was written — the messenger
   * convention, where a portrait sits at the bottom of a speaker's last bubble
   * — and it was chosen without a picture, because no band in this library had
   * ever drawn a portrait here at all (`loom.message` had no fallback until 25
   * September, and the catalogue ships no photographs). The convention assumes
   * a transcript with no name lines in it. This one puts the speaker's name and
   * the time *above* the bubble, so a face pinned three lines below the name it
   * belongs to reads as belonging to nothing.
   */
  message: "loom-message",
  messageBody: "loom-message-body",
  messagePerson: "loom-message-person",
  messageSystem: "loom-message-system",
  /** Its composing indicator, and one dot of the three. */
  messageDots: "loom-message-dots",
  messageDot: "loom-message-dot",
  /**
   * A `loom.reveal`: a band that arrives as the reader scrolls to it, its two
   * variants, and the still rendering it takes while somebody is editing the
   * page.
   *
   * **There is no cascade rule here and the header used to say there was.**
   * Three classes are declared below and a fourth was described; nothing
   * emitted it and nothing could, because a cascade over a reveal's own
   * children would have to reach through the arranger it wraps to find the
   * cells. The effect is real and is got the other way round — a reveal around
   * each cell, each with a view timeline of its own — which `loom.reveal` now
   * explains and `featuresBand` uses. Corrected rather than built.
   *
   * Every rule that sets the starting `opacity: 0` is inside
   * `@supports (animation-timeline: view())`, so a browser that cannot run the
   * animation never hides the content either. That is not tidiness — it is the
   * difference between an entrance and a blank page.
   */
  reveal: "loom-reveal",
  revealFade: "loom-reveal-fade",
  revealStill: "loom-reveal-still",
   /**
   * A `loom.frame`. The chrome itself, which declares the containment its marks
   * are measured against; the screen inside it; and the layer over that screen.
   */
  frame: "loom-frame",
  frameScreen: "loom-frame-screen",
  /**
   * The layer is the whole of what separates a wide frame from a narrow one: an
   * overlay on the screen where there is room, a legend under it where there is
   * not. Both are in this file because a pin cannot know which it is in, the
   * legend is the **unqueried** rule so a client that resolves no query gets the
   * readable one, which is what the rule about a layout CSS alone can express
   * asks for, and the query is the *frame's* width rather than the
   * window's — a screenshot in one column of a split is narrow on the widest
   * screen there is.
   */
  framePins: "loom-frame-pins",
  /** One `loom.pin`: the mark, its dot, its label, and the four sides it may open to. */
  pin: "loom-pin",
  pinDot: "loom-pin-dot",
  pinLabel: "loom-pin-label",
  pinStart: "loom-pin-start",
  pinEnd: "loom-pin-end",
  pinAbove: "loom-pin-above",
  pinBelow: "loom-pin-below",
  /** The still rendering it takes while somebody is editing the page. */
  pinStill: "loom-pin-still",
  /**
   * A `loom.link-trail`. The row, one crumb in it, and the three things that
   * may sit between two crumbs.
   *
   * The separator is a `::before` on the *wrapper* rather than on the link,
   * which is the only reason it can exist: a pseudo-element on the anchor is
   * inside the link, so its glyph joins the link's accessible name and the
   * reader hears "slash Documentation". Which crumbs get one is `+`, and where
   * an element sits among its siblings is a fact no render of one node has.
   */
  trail: "loom-trail",
  trailCrumb: "loom-trail-crumb",
  /** The default: a rotated corner, drawn rather than typed, so nothing announces it. */
  trailChevron: "loom-trail-chevron",
  trailSlash: "loom-trail-slash",
  trailDot: "loom-trail-dot",
  /**
   * A `loom.carousel`: the scroller, one cell in it, and the variant that snaps
   * to the middle.
   *
   * Everything except each cell's width is here, and the width is the one thing
   * that has to be inline because it comes from a prop. The rest — the snapping,
   * the smooth scroll a reduced-motion reader does not get, the focus ring, and
   * the block padding that keeps a card's hover shadow from becoming a vertical
   * scrollbar — is either a state selector or a rule something else has to
   * cancel, and an inline value would beat all of it.
   */
  carousel: "loom-carousel",
  carouselCell: "loom-carousel-cell",
  carouselCentred: "loom-carousel-centred",
  /**
   * A `loom.meter`'s two fills. One custom property carries the proportion, and
   * one keyframe animates it from nothing, so a bar and a ring fill in step and
   * a single rule stops both for a reader who asked for calm.
   *
   * The property is registered with `@property`, which is what makes it
   * animate at all: an unregistered custom property interpolates discretely, so
   * the bar would jump from empty to full in one frame. A browser that does not
   * support the rule still renders the right proportion — the value is on the
   * element — and simply does not animate it, which is the correct way to fail.
   */
  meterFill: "loom-meter-fill",
  meterArc: "loom-meter-arc",
  /**
   * A `loom.book`. The card, the frame the `@container` rule flips, the 2:3
   * cover panel, and the body beside it.
   *
   * `loom-offering-frame`'s reason applies unchanged: the frame's direction is
   * the thing the rule varies, so it must not also be set inline. The cover's
   * `flex` basis is here for the same reason — it is `auto` in the tile
   * rendering and a fixed 7rem in the row one.
   */
  book: "loom-book",
  bookFrame: "loom-book-frame",
  bookCover: "loom-book-cover",
  /**
   * The cover panel when there is no cover, which is not the same object.
   *
   * A 2:3 ratio reserves the shape of a *picture*, and in the tile rendering
   * that is the card's whole width — 350px of blank panel on a phone and 360px
   * in a three-across shelf, per book. `articles-episodes` found the identical
   * fault in `loom.recording` on 23 September and the rule it produced is the
   * one applied here: **a frame with no picture in it does not get the
   * picture's proportions.**
   *
   * What it gets instead is a spine's worth of width at the same ratio, which
   * keeps the object a book rather than deleting it — `loom.book` argues at
   * length that a blank panel reads as *this edition's cover is not to hand*
   * and that a shelf should line up whether or not every cover was found, and
   * both of those stay true at 4.5rem. The row rendering is untouched: its
   * `flex` basis of 7rem beats a width on a flex item, so a card that was
   * already showing a small cover keeps the size it had.
   */
  bookCoverBare: "loom-book-cover-bare",
  bookBody: "loom-book-body",
  /**
   * A `loom.listing`: the photograph, and the flags worn on it. The flags strip
   * is positioned rather than in the flow, so it needs the media panel to be the
   * positioned ancestor, and `:empty` keeps a listing with no flags from
   * carrying an invisible box over its picture.
   */
  listingMedia: "loom-listing-media",
  /**
   * The same panel with no photograph in it, which is only as tall as the flags
   * it carries.
   *
   * `loom.listing` gives its media frame a second job — the flags are worn on
   * it — and that is why the frame is drawn at all when there is no picture. It
   * is not a reason to keep the picture's 4:3, and `features-listings`
   * photographed what keeping it costs: a quarter of every card given to a grey
   * rectangle, six times down a band. The flags come out of the corner and into
   * the flow, the ratio goes, and the strip is as tall as a row of badges.
   *
   * A listing with neither a picture nor a flag draws no frame at all; that is
   * the component's own call, because an empty strip is a rule of dead space
   * above an address.
   */
  listingMediaBare: "loom-listing-media-bare",
  listingFlags: "loom-listing-flags",
  /**
   * The strip of `loom.spec` children under a listing's address, and one
   * `loom.spec` itself.
   *
   * The middot between two specs is the position selector this pair needs and
   * the reason both are here: a render is a total pure projection of one node, so
   * no spec can know it has a sibling. The rule is scoped to a library class, so
   * it reaches nothing else on the host's page — the discipline the rail's
   * `li:last-child` established.
   *
   * **It trails rather than leads, and a screenshot is why.** Written as
   * `.loom-spec + .loom-spec::before` the separator belongs to the *second* of
   * each pair, which is correct until the strip wraps — and then a line begins
   * with a floating middot, which is what a three-specification listing did on a
   * narrow card. As `:not(:last-child)::after` a wrapped line *ends* with the
   * middot, which is how a typesetter would break a run and reads as
   * continuation rather than as a bullet.
   */
  listingSpecs: "loom-listing-specs",
  spec: "loom-spec",
  /**
   * A `loom.halo`'s lit rim, and the same rim with the light travelling round
   * it. Both are here rather than inline for one reason each, and neither is a
   * preference: a gradient *border* is two masks composited against each other,
   * which is a property with no inline spelling that degrades safely, and a
   * travelling light is an animation, which a tree may not carry — motion is a
   * static stylesheet the primitive emits.
   *
   * The gradient rim lives inside an `@supports` test and the fallback outside
   * it is a plain accent border. That order is deliberate rather than tidy:
   * written the other way round, a browser without mask compositing paints the
   * whole gradient as a filled rectangle *over* the content it is supposed to
   * be ringing, because the rim layer sits above the content on purpose.
   */
  haloRing: "loom-halo-ring",
  haloTrace: "loom-halo-trace",
  /**
   * A `loom.emphasis` set as a wash rather than as weight — the accent-washed
   * display type nothing in this library could draw.
   *
   * `background-clip: text` with a transparent fill is one unsupported property
   * away from an invisible word, so the wash is inside an `@supports` test and
   * the declaration outside it is a solid `accent-strong`. The forced-colours
   * rule after it is the second way the same word disappears, and it is the one
   * that cannot be felt by testing in a browser that is behaving normally.
   */
  washed: "loom-washed",
  /**
   * A `loom.waiting-state`. The region that is waiting, and one bar of the
   * shape it is holding open.
   *
   * The sheen is a moving `background-position` over a gradient rather than a
   * travelling pseudo-element, which is what lets one class cover a bar, a
   * circle and a block: it inherits whatever `border-radius` the element sets
   * inline, and a pseudo-element would have needed clipping on each of them.
   *
   * Reduced motion leaves the bar and removes the travel — a waiting state with
   * its animation switched off entirely is still a correct waiting state, which
   * is not true of an entrance, so this one is genuinely optional and is dropped
   * rather than frozen mid-sweep.
   */
  waiting: "loom-waiting",
  waitingBar: "loom-waiting-bar",
  /**
   * A `loom.link-pager`. The row of numbers, and the two ends it places.
   *
   * Every tile property here is one `loom.link` does **not** set inline, which
   * is the file's first trap read forwards rather than discovered afterwards —
   * a container in this library can only add to its children what they left
   * unspoken. The block padding is reachable at all because `loom.link` moved
   * its own 2px off the element and into `.loom-link` on the same day this
   * landed; the underline is switched off here deliberately, since a tile and a
   * wipe-in rule are two marks for one fact.
   */
  pager: "loom-pager",
  pagerNumbers: "loom-pager-numbers",
  /** `loom.link`'s own underline offset, off the element so a container can vary it. */
  link: "loom-link",
  /**
   * A `loom.stat` and its three parts, moved off the element and into here so a
   * second arrangement of the same content model can restyle them.
   *
   * This is `loom.milestone`'s lesson applied a second time, and the rule it
   * rests on is the first mechanic above: **an inline style beats a rule**, so
   * every property a parent might need to change must not also be set on the
   * element. A stat that kept its type inline could be put in a chart and would
   * render its figure at the headline size inside a 12-pixel-wide column.
   *
   * ## The stat is its own container, and that closed a figure running off a phone
   *
   * `.loom-stat` declares `container-type: inline-size` and `.loom-stat-value`
   * takes `min(var(--loom-scale-7), 26cqi)`. Both halves are load-bearing and
   * the second cannot be written without the first: the figure's size has to be
   * capped against **the column the stat is in**, and a grid styles its children
   * rather than wrapping them, so there is no ancestor to declare the
   * containment on. `loom.heading` names this exact hole in its own cap comment
   * — *what is still not held back is a heading in a bare grid cell* — and the
   * answer is that the child declares it for itself.
   *
   * **Found on 27 September, in a band that had been hiding it twice.** A
   * `loom.stat-grid` with `columns: "four"` on a `canvas` section is 358 pixels
   * of content at a 390-pixel viewport, which `auto-fit` splits into two
   * columns of about 166. `"99.98%"` at `--loom-scale-7` in `bold-sans` is
   * about 185 pixels and does not break, so the grid item's automatic minimum
   * size pushed its own track wide: measured `scrollWidth 401 / innerWidth 390`,
   * with the figure visibly off the right edge of the page.
   *
   * Nothing had ever seen it. The catalogue's `metricsBand` uses `tone:
   * "surface"`, whose inline padding narrows the band enough that `auto-fit`
   * drops to **one** column, where the figure fits — and the one specimen that
   * photographs a stat grid on a canvas band wrapped it in a `loom.backdrop`,
   * which clips, so the harness measured 390 against 390. Two independent
   * accidents, each of which alone would have hidden it.
   *
   * The containment does both jobs at once, which is why it is one declaration
   * rather than a `min-width: 0` and a cap: an element with inline-size
   * containment contributes nothing of its contents to track sizing, so the
   * track stops blowing out, *and* `cqi` starts resolving against the column.
   * `26cqi` is sized for a seven-character figure and is inert above a
   * 215-pixel column, which is every stat in a grid on a desktop.
   */
  stat: "loom-stat",
  statValue: "loom-stat-value",
  statLabel: "loom-stat-label",
  statCaption: "loom-stat-caption",
  /** A stat carrying a magnitude, so only a stat that can be plotted grows a bar. */
  statPlotted: "loom-stat-plotted",
  /**
   * A `loom.stat-chart`: the same stats a grid would print in a row, plotted
   * against a scale instead.
   *
   * **The scale is the whole reason this is here rather than inline.** A render
   * is a total pure projection of one node, so the chart cannot read its
   * children's magnitudes and cannot compute a maximum from them. What it can do
   * is declare the ceiling as a custom property and let each bar work out its own
   * height against it — custom properties inherit, so the *browser* does the
   * cross-child arithmetic that the render function is forbidden from doing. It
   * is the bargain a layout CSS alone can express already makes for the mosaic's
   * rhythm, and the one a heading's container-query cap makes for its own width.
   */
  statChart: "loom-stat-chart",
} as const

/**
 * Reduced motion removes movement, never feedback: a `.loom-rise` element ends
 * at `opacity: 1` rather than never arriving, and hover still recolours. An
 * entrance animation that is simply switched off is how a page renders blank
 * for anyone who asked their system to calm it down.
 */
const CSS = `
@property --loom-meter-sweep {
  syntax: "<percentage>";
  inherits: false;
  initial-value: 0%;
}
@keyframes loom-rise {
  from { opacity: 0; transform: translate3d(0, 0.9rem, 0); }
  to { opacity: 1; transform: none; }
}
@keyframes loom-meter-sweep {
  from { --loom-meter-sweep: 0%; }
}
@keyframes loom-orbit {
  from { transform: rotate(0turn); }
  to { transform: rotate(1turn); }
}
@keyframes loom-aurora {
  0% { transform: translate3d(-6%, -4%, 0) scale(1); }
  50% { transform: translate3d(6%, 4%, 0) scale(1.25); }
  100% { transform: translate3d(-6%, -4%, 0) scale(1); }
}
.loom-rise {
  animation: loom-rise calc(var(--loom-motion-slow) * 1.6) cubic-bezier(0.22, 1, 0.36, 1) both;
}
.loom-lift {
  transition: transform var(--loom-motion-medium) ease, box-shadow var(--loom-motion-medium) ease, border-color var(--loom-motion-medium) ease;
}
.loom-lift:hover {
  transform: translate3d(0, -4px, 0);
  box-shadow: 0 24px 48px -34px var(--loom-fg-default);
  border-color: var(--loom-border-accent);
}
@keyframes loom-waiting {
  from { background-position: 200% 0; }
  to { background-position: -200% 0; }
}
.loom-waiting-bar {
  background-color: var(--loom-bg-surface-muted);
  background-image: linear-gradient(90deg, transparent 20%, var(--loom-bg-surface) 50%, transparent 80%);
  background-size: 200% 100%;
  background-repeat: no-repeat;
  animation: loom-waiting calc(var(--loom-motion-slow) * 6) linear infinite;
}
.loom-link {
  padding-block-end: 2px;
}
.loom-pager .loom-link {
  padding-block: var(--loom-spacing-2);
  padding-inline: var(--loom-spacing-3);
  min-width: 1.25rem;
  text-align: center;
  border: 1px solid transparent;
  border-radius: var(--loom-radius-md);
  background-image: none;
  transition: background-color var(--loom-motion-fast) ease, border-color var(--loom-motion-fast) ease;
}
.loom-pager .loom-link:hover, .loom-pager .loom-link:focus-visible {
  background-color: var(--loom-bg-surface);
  border-color: var(--loom-border-subtle);
}
.loom-pager .loom-link[aria-current="page"] {
  background-color: var(--loom-bg-surface);
  border-color: var(--loom-border-accent);
}
.loom-underline {
  background-image: linear-gradient(var(--loom-accent), var(--loom-accent));
  background-repeat: no-repeat;
  background-position: 0 100%;
  background-size: 0% 2px;
  transition: background-size var(--loom-motion-medium) cubic-bezier(0.22, 1, 0.36, 1);
}
.loom-underline:hover, .loom-underline:focus-visible {
  background-size: 100% 2px;
}
.loom-underline[aria-current="page"] {
  background-size: 100% 2px;
}
.loom-aurora {
  animation: loom-aurora calc(var(--loom-motion-slow) * 40) ease-in-out infinite;
}
.loom-marker {
  transition: transform var(--loom-motion-medium) cubic-bezier(0.22, 1, 0.36, 1);
}
details[open] > summary .loom-marker {
  transform: rotate(45deg);
}
.loom-logo-cloud .loom-mark {
  filter: grayscale(1);
  opacity: 0.72;
  transition: filter var(--loom-motion-medium) ease, opacity var(--loom-motion-medium) ease;
}
.loom-logo-cloud .loom-mark:hover,
.loom-logo-cloud a:hover > .loom-mark,
.loom-logo-cloud a:focus-visible > .loom-mark {
  filter: none;
  opacity: 1;
}
.loom-milestone {
  display: grid;
  grid-template-columns: 5.5rem auto 1fr;
  column-gap: var(--loom-spacing-3);
}
.loom-milestone > .loom-rail-marker {
  text-align: end;
}
.loom-rail:not(:has(> li > .loom-rail-marker:not(:empty))) > .loom-milestone {
  grid-template-columns: auto 1fr;
}
.loom-rail:not(:has(> li > .loom-rail-marker:not(:empty))) > .loom-milestone > .loom-rail-marker {
  display: none;
}
@container (max-width: 26rem) {
  .loom-rail:has(> li > .loom-rail-marker:not(:empty)) > .loom-milestone {
    grid-template-columns: auto 1fr;
    row-gap: var(--loom-spacing-1);
  }
  .loom-rail:has(> li > .loom-rail-marker:not(:empty)) > .loom-milestone > .loom-rail-marker {
    grid-column: 2;
    grid-row: 1;
    text-align: start;
  }
  .loom-rail:has(> li > .loom-rail-marker:not(:empty)) > .loom-milestone > .loom-rail-track {
    grid-column: 1;
    grid-row: 1 / span 2;
  }
  .loom-rail:has(> li > .loom-rail-marker:not(:empty)) > .loom-milestone > .loom-rail-body {
    grid-column: 2;
    grid-row: 2;
  }
  .loom-rail:has(> li > .loom-rail-marker:not(:empty)) .loom-rail-dot {
    margin-block-start: 0.3em;
  }
}
.loom-milestone > .loom-rail-track {
  flex-direction: column;
}
.loom-rail-dot {
  margin-block-start: 0.45em;
}
.loom-rail-line {
  flex: 1 1 auto;
  width: 2px;
}
.loom-milestone-row {
  display: flex;
  flex-wrap: wrap;
}
.loom-milestone-row > .loom-milestone {
  flex: 1 1 14rem;
  grid-template-columns: 1fr;
  row-gap: var(--loom-spacing-2);
  align-content: start;
}
.loom-milestone-row > .loom-milestone > .loom-rail-track {
  order: 1;
  flex-direction: row;
}
.loom-milestone-row > .loom-milestone > .loom-rail-marker {
  order: 2;
  text-align: start;
}
.loom-milestone-row > .loom-milestone > .loom-rail-body {
  order: 3;
}
.loom-milestone-row .loom-rail-dot {
  margin-block-start: 0;
}
.loom-milestone-row .loom-rail-line {
  width: auto;
  height: 2px;
}
.loom-milestone-row > li:last-child .loom-rail-line {
  visibility: hidden;
}
.loom-rail {
  container-type: inline-size;
}
.loom-rail > li .loom-rail-body {
  padding-block-end: var(--loom-spacing-5);
}
.loom-rail-tight > li .loom-rail-body {
  padding-block-end: var(--loom-spacing-3);
}
.loom-rail > li:last-child .loom-rail-body {
  padding-block-end: 0;
}
.loom-rail > li:last-child .loom-rail-line, .loom-rail-none .loom-rail-line {
  visibility: hidden;
}
.loom-frame-adaptive {
  aspect-ratio: 3 / 4;
}
@container (min-width: 36rem) {
  .loom-frame-adaptive {
    aspect-ratio: 16 / 10;
  }
}
.loom-cover {
  position: relative;
  flex-direction: column;
}
.loom-cover > .loom-cover-body {
  flex: 1 1 auto;
}
.loom-cover-link::after {
  content: "";
  position: absolute;
  inset: 0;
}
.loom-cover-media {
  aspect-ratio: 16 / 10;
  overflow: hidden;
}
.loom-lead > article:first-of-type {
  grid-column: 1 / -1;
  flex-direction: row;
  flex-wrap: wrap;
}
.loom-lead > article:first-of-type > .loom-cover-media,
.loom-lead > article:first-of-type > .loom-cover-body {
  flex: 1 1 20rem;
}
.loom-lead > article:first-of-type > .loom-cover-media {
  aspect-ratio: auto;
  min-height: 16rem;
}
.loom-input {
  transition: border-color var(--loom-motion-medium) ease;
}
.loom-input:hover {
  border-color: var(--loom-border-strong);
}
.loom-input:focus-visible {
  outline: 2px solid var(--loom-border-accent);
  outline-offset: 2px;
  border-color: var(--loom-border-accent);
}
.loom-input::placeholder {
  color: var(--loom-fg-muted);
  opacity: 1;
}
.loom-input:disabled {
  cursor: not-allowed;
}
.loom-select::after {
  content: "";
  position: absolute;
  inset-inline-end: var(--loom-spacing-3);
  inset-block-start: 50%;
  width: 0.42em;
  height: 0.42em;
  border-inline-end: 2px solid currentColor;
  border-block-end: 2px solid currentColor;
  transform: translate3d(0, -70%, 0) rotate(45deg);
  color: var(--loom-fg-muted);
  pointer-events: none;
}
.loom-form-inline > .loom-field {
  flex: 1 1 14rem;
}
.loom-cluster > * + * {
  margin-inline-start: -0.7em;
}
.loom-cluster > * {
  box-shadow: 0 0 0 2px var(--loom-bg-canvas);
}
/*
 * The scrolling region, shared by the two tables that have one.
 *
 * loom.carousel settled the shape of this on 28 August and the reasoning is
 * in that file: a scroll container is focusable by default in some browsers and
 * not in others, so it is made focusable and named rather than left to the
 * browser, and it does not fade at its edges because a mask at rest washes out
 * content that has fully arrived. The affordance is the peek instead -- the
 * next thing along is always visibly cut off -- which is why the criterion
 * column narrows further down this file rather than a gradient being drawn over
 * the band's trailing edge.
 *
 * scroll-padding-inline-start is the one line here a carousel has no use for.
 * A comparison keeps its criterion in place while the subjects travel under it,
 * so a subject scrolled to the start of the region arrives *underneath* the
 * question it is answering. The padding is the sticky column's own width, so a
 * snap lands the subject beside its criterion instead of behind it.
 *
 * Proximity rather than the carousel's mandatory, and it is the one place
 * the two deliberately differ. A carousel is read one item at a time. A
 * comparison is read by holding two subjects side by side, and mandatory snap
 * takes that position away from a reader the moment they let go.
 */
.loom-scroll-x {
  overflow-x: auto;
  min-width: 0;
  scroll-snap-type: inline proximity;
  overscroll-behavior-inline: contain;
  scrollbar-width: thin;
  scrollbar-color: var(--loom-border-default) transparent;
}
/*
 * The ring is drawn *inside* the region, which is the one place this differs
 * from the carousel's and it is not a preference.
 *
 * Both bands clip themselves: a panel rounds its corners and sets overflow:
 * hidden to make the table's corners follow, and that wrapper is the scroller's
 * parent. An outline offset outwards is therefore drawn in the two pixels the
 * parent is clipping, so the focus stop this run added would have been a focus
 * stop with no visible ring -- which is worse than the unreachable region it
 * replaced, because a keyboard reader would now land somewhere and be told
 * nothing. Negative offset puts the ring on the region's own inside edge, where
 * nothing is clipping it.
 */
.loom-scroll-x:focus-visible {
  outline: 2px solid var(--loom-accent);
  outline-offset: -2px;
}
.loom-compare-scroll {
  scroll-padding-inline-start: 12rem;
}
.loom-compare th, .loom-compare td {
  padding: var(--loom-spacing-3) var(--loom-spacing-4);
}
/*
 * Every cell is a snap position except the one that never moves. A sticky
 * element is a poor snap target -- it is at the start of the region by
 * definition, so snapping to it is snapping to where the reader already is --
 * and the positions worth landing on are the subjects travelling under it.
 */
.loom-compare tbody > tr > *:not(.loom-compare-key), .loom-compare thead > tr > * {
  scroll-snap-align: start;
}
/*
 * The two widths that decide whether this band fits a phone, moved here from
 * the elements that used to set them inline.
 *
 * That was [0155](../../decisions/0155-a-container-may-only-add-to-its-children-what-they-left-unspoken.md)
 * being broken in the second place it has now been found: loom.comparison
 * set min-width: 7rem on every answer and loom.comparison-row set
 * min-width: 12rem on every criterion, so the two numbers that decide what a
 * 390px reader sees were the only two in the band no rule in this file could
 * reach. Both comments called the pair "the intrinsic answer to a narrow
 * screen, with no width query to declare" -- and they were right that the
 * arithmetic belongs to the content, and wrong that it never varies, because a
 * criterion that reads as a sentence at 1280 is a criterion that eats the
 * answer beside it at 390.
 *
 * Nothing about the band's wide rendering changes: these are the same two
 * values, in the same two places, said somewhere a media query can reach them.
 */
.loom-compare th, .loom-compare td {
  min-width: 7rem;
}
.loom-compare .loom-compare-key {
  min-width: 12rem;
}
/*
 * The peek, which is the whole of the 13 September finding's fix.
 *
 * At 390px the criterion took 192 of the band's 348 pixels and the first
 * subject took 112, leaving a 44-pixel sliver of the second -- and the sliver
 * was *blank*, because an answer is centred in its cell and 44 pixels of a
 * 112-pixel cell is its padding. So the band did have a peek and the peek had
 * no ink in it, which is why a reader could look straight at a four-subject
 * comparison and come away certain there was one.
 *
 * Nine rem instead of twelve puts 92 pixels of the second subject on screen at
 * rest, which is past the centre of that cell and therefore past its mark. It
 * is the same affordance loom.carousel chose over a fade -- the next thing
 * along is always visibly cut off -- and it is only sayable at all because the
 * two widths above stopped being inline styles.
 */
@media (max-width: 47.99rem) {
  .loom-compare .loom-compare-key {
    min-width: 9rem;
  }
  .loom-compare-scroll {
    scroll-padding-inline-start: 9rem;
  }
}
.loom-compare-tight th, .loom-compare-tight td {
  padding: var(--loom-spacing-2) var(--loom-spacing-3);
}
.loom-compare thead > tr > * {
  border-block-end: 1px solid var(--loom-border-strong);
}
.loom-compare tbody > tr + tr > * {
  border-block-start: 1px solid var(--loom-border-default);
}
.loom-compare-key {
  position: sticky;
  inset-inline-start: 0;
  background: var(--loom-bg-surface);
  z-index: 1;
}
.loom-compare-row > * {
  transition: background-color var(--loom-motion-medium) ease;
}
.loom-compare-row:hover > * {
  background: var(--loom-bg-surface-muted);
}
.loom-compare-note, .loom-compare-no {
  color: var(--loom-fg-subtle);
}
.loom-compare-yes {
  color: var(--loom-accent-strong);
}
.loom-compare-partial {
  color: var(--loom-fg-muted);
}
.loom-compare-feature-1 tr > *:nth-child(2),
.loom-compare-feature-2 tr > *:nth-child(3),
.loom-compare-feature-3 tr > *:nth-child(4),
.loom-compare-feature-4 tr > *:nth-child(5) {
  background: var(--loom-accent-subtle);
  border-inline: 1px solid var(--loom-border-accent);
}
.loom-compare-feature-1 tr > *:nth-child(2) .loom-compare-note,
.loom-compare-feature-2 tr > *:nth-child(3) .loom-compare-note,
.loom-compare-feature-3 tr > *:nth-child(4) .loom-compare-note,
.loom-compare-feature-4 tr > *:nth-child(5) .loom-compare-note,
.loom-compare-feature-1 tr > *:nth-child(2) .loom-compare-no,
.loom-compare-feature-2 tr > *:nth-child(3) .loom-compare-no,
.loom-compare-feature-3 tr > *:nth-child(4) .loom-compare-no,
.loom-compare-feature-4 tr > *:nth-child(5) .loom-compare-no {
  color: var(--loom-fg-muted);
}
.loom-list {
  margin: 0;
}
.loom-list > li::marker {
  color: var(--loom-accent);
}
.loom-list > li + li {
  margin-block-start: var(--loom-spacing-2);
}
.loom-list-tight > li + li {
  margin-block-start: var(--loom-spacing-1);
}
.loom-list-loose > li + li {
  margin-block-start: var(--loom-spacing-4);
}
.loom-list .loom-list {
  margin-block-start: var(--loom-spacing-2);
}
.loom-table th, .loom-table td {
  padding: var(--loom-spacing-3) var(--loom-spacing-4);
}
.loom-table-tight th, .loom-table-tight td {
  padding: var(--loom-spacing-2) var(--loom-spacing-3);
}
.loom-table-loose th, .loom-table-loose td {
  padding: var(--loom-spacing-4) var(--loom-spacing-5);
}
.loom-table thead > tr > * {
  border-block-end: 1px solid var(--loom-border-strong);
}
.loom-table tbody > tr + tr > * {
  border-block-start: 1px solid var(--loom-border-default);
}
.loom-table-grid tr > * + * {
  border-inline-start: 1px solid var(--loom-border-default);
}
.loom-table-flush thead > tr > *, .loom-table-flush tbody > tr + tr > * {
  border-block: 0;
}
.loom-table tbody > tr > *:not(.loom-table-key), .loom-table thead > tr > * {
  scroll-snap-align: start;
}
/*
 * A table of sentences, below the width where a phone starts squeezing them.
 *
 * Measured at 390px before this rule: three prose columns at 108, 116 and 125
 * pixels, and one row 360 pixels tall -- 43% of the screen for a single row,
 * and the band did not even have to scroll to do it. With this measure the same
 * row is 193 and the band scrolls 492 inside 348, which is the trade the rule
 * makes: about a screen and a half of horizontal travel a reader controls, in
 * place of vertical height they do not.
 *
 * **Twelve rem rather than ten, chosen by measuring both.** Ten cut the row to
 * 241 and twelve cuts it to 193, for 64 more pixels of travel -- and twelve is
 * the criterion column's own width one rule up, picked there for the same
 * reason a year earlier: wide enough to read as a sentence rather than as a
 * stack of words.
 *
 * **Scoped to the body deliberately.** A row heading is a label rather than a
 * sentence -- "In the tree", "Sep 8" -- and giving it the same measure would
 * spend twelve rem of a phone's width on two words and push the first real
 * column off the screen, which is the defect above with a different cell in
 * it. Measured: the heading column stays at 108 pixels and the two prose
 * columns take 192 each.
 */
@media (max-width: 47.99rem) {
  .loom-table-prose tbody > tr > td {
    min-width: 12rem;
  }
}
.loom-table-row > * {
  transition: background-color var(--loom-motion-medium) ease;
}
.loom-table-row:hover > * {
  background: var(--loom-bg-surface-muted);
}
.loom-table-highlight > * {
  background: var(--loom-accent-subtle);
}
.loom-table-panel .loom-table-key {
  position: sticky;
  inset-inline-start: 0;
  background: var(--loom-bg-surface);
  z-index: 1;
}
.loom-table-panel .loom-table-highlight .loom-table-key {
  background: var(--loom-accent-subtle);
}
@keyframes loom-marquee {
  from { transform: translate3d(0, 0, 0); }
  to { transform: translate3d(-50%, 0, 0); }
}
.loom-marquee {
  container-type: inline-size;
}
.loom-marquee-run > * {
  max-inline-size: min(32rem, 80cqi);
}
.loom-marquee-track {
  display: flex;
  width: max-content;
  animation: loom-marquee calc(var(--loom-motion-slow) * 9) linear infinite;
}
.loom-marquee-run {
  display: flex;
  flex: 0 0 auto;
  align-items: center;
  gap: var(--loom-marquee-gap);
  padding-inline-end: var(--loom-marquee-gap);
}
.loom-marquee-reverse {
  animation-direction: reverse;
}
.loom-marquee-faded {
  -webkit-mask-image: linear-gradient(to right, transparent 0, black 8%, black 92%, transparent 100%);
  mask-image: linear-gradient(to right, transparent 0, black 8%, black 92%, transparent 100%);
}
.loom-marquee:hover .loom-marquee-track, .loom-marquee:focus-within .loom-marquee-track {
  animation-play-state: paused;
}
.loom-marquee-track:has(> * > :nth-child(2)) { animation-duration: calc(var(--loom-motion-slow) * 18); }
.loom-marquee-track:has(> * > :nth-child(3)) { animation-duration: calc(var(--loom-motion-slow) * 27); }
.loom-marquee-track:has(> * > :nth-child(4)) { animation-duration: calc(var(--loom-motion-slow) * 36); }
.loom-marquee-track:has(> * > :nth-child(5)) { animation-duration: calc(var(--loom-motion-slow) * 45); }
.loom-marquee-track:has(> * > :nth-child(6)) { animation-duration: calc(var(--loom-motion-slow) * 54); }
.loom-marquee-track:has(> * > :nth-child(7)) { animation-duration: calc(var(--loom-motion-slow) * 63); }
.loom-marquee-track:has(> * > :nth-child(8)) { animation-duration: calc(var(--loom-motion-slow) * 72); }
.loom-marquee-track:has(> * > :nth-child(9)) { animation-duration: calc(var(--loom-motion-slow) * 81); }
.loom-marquee-track:has(> * > :nth-child(10)) { animation-duration: calc(var(--loom-motion-slow) * 90); }
.loom-marquee-track:has(> * > :nth-child(11)) { animation-duration: calc(var(--loom-motion-slow) * 99); }
.loom-marquee-track:has(> * > :nth-child(12)) { animation-duration: calc(var(--loom-motion-slow) * 108); }
.loom-marquee-track:has(> * > :nth-child(13)) { animation-duration: calc(var(--loom-motion-slow) * 117); }
.loom-marquee-track:has(> * > :nth-child(14)) { animation-duration: calc(var(--loom-motion-slow) * 126); }
.loom-marquee-track:has(> * > :nth-child(15)) { animation-duration: calc(var(--loom-motion-slow) * 135); }
.loom-marquee-track:has(> * > :nth-child(16)) { animation-duration: calc(var(--loom-motion-slow) * 144); }
.loom-marquee-still {
  -webkit-mask-image: none;
  mask-image: none;
}
.loom-marquee-still .loom-marquee-track {
  animation: none;
  display: block;
  width: auto;
}
.loom-marquee-still .loom-marquee-run {
  flex-wrap: wrap;
  /** Nothing to tile against: one run, no echo. The trailing gap would be a dead column. */
  padding-inline-end: 0;
}
.loom-offering {
  container-type: inline-size;
}
.loom-offering-frame {
  display: flex;
  flex-direction: column;
  gap: var(--loom-spacing-4);
  height: 100%;
}
.loom-offering-body {
  flex: 1 1 auto;
  min-inline-size: 0;
}
.loom-offering-action {
  display: grid;
  margin-block-start: auto;
}
@container (min-width: 40rem) {
  .loom-offering-frame {
    flex-direction: row;
    align-items: center;
    gap: var(--loom-spacing-5);
  }
  .loom-offering-action {
    flex: 0 0 auto;
    margin-block-start: 0;
  }
}
.loom-credential {
  position: relative;
}
.loom-recording {
  position: relative;
  container-type: inline-size;
}
.loom-recording-frame {
  display: flex;
  flex-direction: column;
  height: 100%;
}
.loom-recording-art {
  position: relative;
  flex: 0 0 auto;
  overflow: hidden;
}
.loom-recording-body {
  display: flex;
  flex-direction: column;
  gap: var(--loom-spacing-2);
  flex: 1 1 auto;
  min-inline-size: 0;
}
.loom-recording-play {
  position: absolute;
  inset-block-start: 50%;
  inset-inline-start: 50%;
  display: grid;
  place-items: center;
  inline-size: 2.75rem;
  block-size: 2.75rem;
  border-radius: 50%;
  transform: translate(-50%, -50%);
  transition: transform var(--loom-motion-medium) cubic-bezier(0.22, 1, 0.36, 1);
}
.loom-recording:hover .loom-recording-play, .loom-recording:focus-within .loom-recording-play {
  transform: translate(-50%, -50%) scale(1.12);
}
.loom-recording-time {
  position: absolute;
  inset-block-end: var(--loom-spacing-2);
  inset-inline-end: var(--loom-spacing-2);
}
@container (min-width: 34rem) {
  .loom-recording-frame {
    flex-direction: row;
    align-items: flex-start;
  }
  .loom-recording-art {
    inline-size: 11rem;
  }
}
.loom-event {
  container-type: inline-size;
}
.loom-event-frame {
  display: flex;
  flex-direction: column;
  gap: var(--loom-spacing-3);
  height: 100%;
}
.loom-event-when {
  flex: 0 0 auto;
}
.loom-event-body {
  display: flex;
  flex-direction: column;
  gap: var(--loom-spacing-2);
  flex: 1 1 auto;
  min-inline-size: 0;
}
.loom-event-action {
  display: grid;
  margin-block-start: auto;
}
@container (min-width: 40rem) {
  .loom-event-frame {
    flex-direction: row;
    align-items: center;
    gap: var(--loom-spacing-5);
  }
  .loom-event-when {
    inline-size: 9rem;
    align-self: stretch;
    border-inline-end: 1px solid var(--loom-border-default);
    padding-inline-end: var(--loom-spacing-5);
  }
  .loom-event-action {
    flex: 0 0 auto;
    margin-block-start: 0;
  }
}
.loom-nav-menu {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--loom-spacing-5);
}
.loom-nav-toggle {
  display: none;
}
.loom-nav-toggle:empty {
  display: none;
}
@media (max-width: 47.99rem) {
  .loom-nav-toggle {
    display: block;
    margin-inline-start: auto;
  }
  .loom-nav:not(:has(.loom-nav-toggle > *)) .loom-nav-actions {
    margin-inline-start: auto;
  }
  .loom-nav-menu {
    order: 1;
    flex-basis: 100%;
    flex-direction: column;
    align-items: flex-start;
    gap: var(--loom-spacing-3);
  }
  .loom-nav:has(.loom-nav-toggle [data-loom-disclosed="false"]) .loom-nav-menu {
    display: none;
  }
}
/**
 * The three presentations. Each pair is the region's own box followed by the one
 * rule that hides it, written in the only direction that is safe on a page
 * served without scripting — see \`presentation.ts\`.
 */
.loom-popover-panel {
  display: flex;
  flex-direction: column;
}
.loom-popover[data-loom-presented="false"] > .loom-popover-panel {
  display: none;
}
.loom-menu-panel {
  display: flex;
  flex-direction: column;
  align-items: stretch;
}
.loom-menu[data-loom-presented="false"] > .loom-menu-panel {
  display: none;
}
/**
 * A menu row. After \`.loom-link\` in this file on purpose: the two selectors
 * weigh the same, so the later one is what gives a row its hit area instead of
 * the two pixels a link reserves for its underline. \`background-image: none\`
 * is the underline itself, which would wipe in under a row already painting a
 * background of its own.
 */
.loom-menu-panel > * {
  padding-block: var(--loom-spacing-2);
  padding-inline: var(--loom-spacing-3);
  border-radius: var(--loom-radius-sm);
  background-image: none;
  transition: background-color var(--loom-motion-fast) ease;
}
.loom-menu-panel > *:hover, .loom-menu-panel > *:focus-visible {
  background-color: var(--loom-bg-surface-muted);
}
.loom-lightbox > .loom-control-present {
  position: absolute;
  inset-block-end: var(--loom-spacing-3);
  inset-inline-end: var(--loom-spacing-3);
  z-index: 2;
}
/**
 * The frame, and the two tracks are not decoration.
 *
 * \`display: grid\` with implicit tracks sizes its one column to the **max-content
 * of the plate inside it**, so a paragraph in the opened region computed its
 * widest unbroken width, the track grew to match, and the plate — capped at
 * 64rem — clipped it and scrolled sideways. \`minmax(0, 1fr)\` is the standard
 * answer: it lets the track be the frame's own size and the content wrap inside
 * it. Found by photographing it; the picture blamed the plate.
 */
.loom-lightbox-frame {
  display: grid;
  grid-template-columns: minmax(0, 1fr);
  grid-template-rows: minmax(0, 1fr);
  place-items: center;
}
.loom-lightbox[data-loom-presented="false"] > .loom-lightbox-frame {
  display: none;
}
/**
 * The scroll lock, and the only rule in this file that reaches the document
 * element — 0210. It is scoped by a library class inside the \`:has()\`, so it
 * applies while a Loom lightbox is open and at no other time, and it is the one
 * thing a modal owes a reader that the behaviour seam leaves to the primitive
 * and a stylesheet can actually hold.
 */
html:has(.loom-lightbox[data-loom-presented="true"]) {
  overflow: hidden;
}
/**
 * The wipe's slider, over the foot of the band. A control paints itself inline,
 * so a primitive can only place it from here.
 */
.loom-before-after > .loom-control-adjust {
  position: absolute;
  inset-block-end: var(--loom-spacing-3);
  inset-inline-start: 50%;
  transform: translateX(-50%);
  inline-size: min(18rem, 70%);
  z-index: 2;
}
.loom-feature {
  container-type: inline-size;
}
.loom-feature-frame {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: var(--loom-spacing-3);
  flex: 1 1 auto;
  min-inline-size: 0;
  inline-size: 100%;
}
.loom-feature-copy {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: var(--loom-spacing-3);
  min-inline-size: 0;
}
.loom-feature-media {
  min-inline-size: 0;
  inline-size: 100%;
}
/*
 * The turn, and the number.
 *
 * 44rem is the width at which a 20rem column of words and a picture beside it
 * are both still worth having. Below it the two would be about 15rem each,
 * which is a paragraph four words wide next to a panel too narrow to read, so
 * the tile stays a column -- and a cell of an ordinary loom.feature-grid,
 * which is around 21rem, never reaches it at all.
 *
 * The words take the smaller share deliberately. The picture is the thing the
 * wide cell was widened for; a tile that gave the copy half of 1120px would be
 * a line of 90 characters, which is the fault READABLE_MEASURE exists to
 * avoid one level up.
 */
@container (min-width: 44rem) {
  .loom-feature-figured {
    flex-direction: row;
    align-items: center;
    gap: var(--loom-spacing-5);
  }
  .loom-feature-figured > .loom-feature-copy {
    flex: 1 1 18rem;
  }
  .loom-feature-figured > .loom-feature-media {
    flex: 1.35 1 22rem;
  }
}
.loom-mosaic {
  display: grid;
  grid-template-columns: repeat(6, 1fr);
  align-items: stretch;
  container-type: inline-size;
}
/*
 /**
 * One column until the *band* has room for six, never until the screen does.
 *
 * A container query reads an ancestor rather than the element that declared
 * containment, so grid-template-columns -- which lives on the mosaic itself --
 * cannot be inside the query. The six tracks are therefore unconditional and it
 * is the *cells* that are switched: full-width by default, and cut into the
 * rhythm's spans only where the band is wide enough to hold them. That is also
 * the safe way round, because a browser that does not understand a container
 * query falls back to one cell per row rather than to six columns on a phone.
 */
.loom-mosaic > * {
  grid-column: span 6;
}
@container (min-width: 48rem) {
  .loom-mosaic-alternating > *:nth-child(4n + 1),
  .loom-mosaic-alternating > *:nth-child(4n) {
    grid-column: span 4;
  }
  .loom-mosaic-alternating > *:nth-child(4n + 2),
  .loom-mosaic-alternating > *:nth-child(4n + 3) {
    grid-column: span 2;
  }
  .loom-mosaic-showcase > *:nth-child(5n + 1),
  .loom-mosaic-showcase > *:nth-child(5n + 2) {
    grid-column: span 3;
  }
  .loom-mosaic-showcase > *:nth-child(5n + 3),
  .loom-mosaic-showcase > *:nth-child(5n + 4),
  .loom-mosaic-showcase > *:nth-child(5n) {
    grid-column: span 2;
  }
  /*
   /**
   * Two classes rather than one, so this rule outranks the unconditional
   * .loom-mosaic > * above on specificity rather than on source order -- the
   * only rhythm rule whose selector would otherwise tie with it.
   */
  .loom-mosaic.loom-mosaic-lead > * {
    grid-column: span 2;
  }
  .loom-mosaic-lead > *:first-child {
    grid-column: span 6;
  }
}
.loom-orbit {
  position: relative;
  aspect-ratio: 1;
  width: 100%;
  container-type: inline-size;
}
.loom-orbit-guide, .loom-orbit-seat {
  position: absolute;
  --loom-orbit-radius: 38%;
  /*
   * The same radius as a length rather than as a percentage, and it is needed
   * because a percentage on a seat's own connector would resolve against the
   * seat -- a box the size of a word -- instead of against the stage. cqi is
   * the stage's inline size, which is what 38% was a percentage of, so the two
   * declarations are one number written twice and have to stay equal.
   */
  --loom-orbit-reach: 38cqi;
}
.loom-orbit-inner {
  --loom-orbit-radius: 22%;
  --loom-orbit-reach: 22cqi;
}
/*
 * border-default and not border-subtle, which is the repair a photograph made.
 *
 * The guides are this band's argument -- they are what makes eight marks read
 * as an orbit rather than as scattered logos -- and on the bold palette
 * border-subtle is five points of luminance away from the surface it is drawn
 * against, which is a line nobody has ever seen. The primitive said the guides
 * were the thing holding the arrangement together and under one of the two
 * starter palettes it was drawing nothing at all. The numbers are in the
 * 26 September finding; they cannot be written here, because a hex literal
 * inside this sheet is indistinguishable from a hardcoded colour to the test
 * that forbids one.
 */
.loom-orbit-guide {
  inset: calc(50% - var(--loom-orbit-radius));
  border: 1px dashed var(--loom-border-default);
  border-radius: 50%;
  pointer-events: none;
}
.loom-orbit-seat {
  inset-inline-start: calc(50% + var(--loom-orbit-x) * var(--loom-orbit-radius));
  inset-block-start: calc(50% + var(--loom-orbit-y) * var(--loom-orbit-radius));
  transform: translate(-50%, -50%);
}
/*
 * One connector, drawn from the seat back to the middle rather than from the
 * middle out to the seat.
 *
 * It is on the seat because that is the element that already knows where it
 * sits: the angle is the seat's own, so the line is one rotation of a box
 * anchored at the seat's centre and turned a half-turn past its bearing. Drawn
 * from the stage instead, every connector would need the seat's angle passed
 * back up, and the stage has no element per child to put it on.
 *
 * It is under the mark because the mark is painted after the turning layer and
 * on its own ground: a connector that stopped short of the middle would be a
 * line pointing at nothing, and one that crossed it would be drawn over the
 * name of the thing it is pointing at.
 */
.loom-orbit-spoked .loom-orbit-seat::before {
  content: "";
  position: absolute;
  inset-inline-start: 50%;
  inset-block-start: 50%;
  inline-size: var(--loom-orbit-reach);
  block-size: 0;
  border-block-start: 1px dashed var(--loom-border-default);
  transform-origin: 0 0;
  transform: rotate(calc(var(--loom-orbit-angle) * 1deg + 180deg));
  pointer-events: none;
}
@container (max-width: 26rem) {
  .loom-orbit-inner {
    --loom-orbit-radius: 38%;
    --loom-orbit-reach: 38cqi;
  }
  .loom-orbit-guide.loom-orbit-inner {
    display: none;
  }
}
.loom-orbit-spinner {
  position: absolute;
  inset: 0;
  animation: loom-orbit calc(var(--loom-motion-slow) * 80) linear infinite;
}
.loom-orbit-item {
  display: grid;
  place-items: center;
  animation: loom-orbit calc(var(--loom-motion-slow) * 80) linear infinite reverse;
}
.loom-orbit-reverse .loom-orbit-spinner {
  animation-direction: reverse;
}
.loom-orbit-reverse .loom-orbit-item {
  animation-direction: normal;
}
.loom-orbit-still .loom-orbit-spinner, .loom-orbit-still .loom-orbit-item {
  animation: none;
}
@keyframes loom-message-dot {
  0%, 64%, 100% { opacity: 0.35; transform: none; }
  32% { opacity: 1; transform: translate3d(0, -0.2rem, 0); }
}
.loom-message {
  display: flex;
  align-items: flex-start;
  gap: var(--loom-spacing-3);
  margin: 0;
  list-style: none;
}
.loom-message-person {
  flex-direction: row-reverse;
}
.loom-message-system {
  justify-content: center;
}
.loom-message-body {
  display: flex;
  flex-direction: column;
  gap: var(--loom-spacing-2);
  min-width: 0;
  max-inline-size: min(100%, 46ch);
}
.loom-message-person > .loom-message-body {
  align-items: flex-end;
}
.loom-message-system > .loom-message-body {
  align-items: center;
  max-inline-size: min(100%, 62ch);
}
.loom-message-dot {
  animation: loom-message-dot calc(var(--loom-motion-slow) * 1.4) ease-in-out infinite;
}
.loom-message-dot:nth-child(2) {
  animation-delay: calc(var(--loom-motion-medium) * 0.5);
}
.loom-message-dot:nth-child(3) {
  animation-delay: var(--loom-motion-medium);
}
@keyframes loom-reveal-rise {
  from { opacity: 0; transform: translate3d(0, 1.5rem, 0); }
  to { opacity: 1; transform: none; }
}
@keyframes loom-reveal-fade {
  from { opacity: 0; }
  to { opacity: 1; }
}
@supports (animation-timeline: view()) {
  .loom-reveal:not(.loom-reveal-still) {
    animation-name: loom-reveal-rise;
    animation-duration: auto;
    animation-timing-function: cubic-bezier(0.33, 0, 0.67, 1);
    animation-fill-mode: both;
    animation-timeline: view();
    animation-range: entry 0% entry 92%;
  }
  .loom-reveal-fade:not(.loom-reveal-still) {
    animation-name: loom-reveal-fade;
  }
}
@media print {
  .loom-reveal:not(.loom-reveal-still) {
    animation: none;
    opacity: 1;
    transform: none;
  }
}
@keyframes loom-pin-pulse {
  0% { transform: scale(1); opacity: 0.5; }
  70%, 100% { transform: scale(2.2); opacity: 0; }
}
.loom-frame {
  container-type: inline-size;
}
.loom-frame-pins {
  display: flex;
  flex-direction: column;
  gap: var(--loom-spacing-2);
  padding: var(--loom-spacing-3);
  border-block-start: 1px solid var(--loom-border-default);
}
.loom-frame-pins:empty {
  display: none;
}
.loom-pin {
  display: flex;
  align-items: center;
  gap: var(--loom-spacing-2);
}
.loom-pin-dot {
  position: relative;
  display: grid;
  place-items: center;
  flex: 0 0 auto;
  min-width: 1.5rem;
  height: 1.5rem;
  padding-inline: 0.3rem;
  border-radius: var(--loom-radius-full);
  line-height: 1;
}
.loom-pin-dot::after {
  content: "";
  position: absolute;
  inset: 0;
  border: 2px solid var(--loom-accent);
  border-radius: inherit;
  pointer-events: none;
  animation: loom-pin-pulse calc(var(--loom-motion-slow) * 7) ease-out infinite;
}
.loom-pin-label {
  display: inline-block;
  padding: var(--loom-spacing-1) var(--loom-spacing-2);
}
.loom-pin-still .loom-pin-dot::after {
  animation: none;
}
@container (min-width: 40rem) {
  .loom-frame-pins {
    position: absolute;
    inset: 0;
    display: block;
    padding: 0;
    border-block-start: 0;
    pointer-events: none;
  }
  .loom-pin {
    position: absolute;
    inset-inline-start: var(--loom-pin-x);
    inset-block-start: var(--loom-pin-y);
    display: grid;
    place-items: center;
    transform: translate(-50%, -50%);
    pointer-events: auto;
  }
  .loom-pin-label {
    position: absolute;
    max-width: 14rem;
    white-space: nowrap;
  }
  .loom-pin-start .loom-pin-label, .loom-pin-end .loom-pin-label {
    inset-block-start: 50%;
    transform: translateY(-50%);
  }
  .loom-pin-end .loom-pin-label {
    inset-inline-start: calc(100% + var(--loom-spacing-2));
  }
  .loom-pin-start .loom-pin-label {
    inset-inline-end: calc(100% + var(--loom-spacing-2));
  }
  .loom-pin-above .loom-pin-label, .loom-pin-below .loom-pin-label {
    inset-inline-start: 50%;
    transform: translateX(-50%);
  }
  .loom-pin-above .loom-pin-label {
    inset-block-end: calc(100% + var(--loom-spacing-2));
  }
  .loom-pin-below .loom-pin-label {
    inset-block-start: calc(100% + var(--loom-spacing-2));
  }
}
.loom-book {
  container-type: inline-size;
}
.loom-book-frame {
  display: flex;
  flex-direction: column;
  gap: var(--loom-spacing-4);
  height: 100%;
}
.loom-book-cover {
  aspect-ratio: 2 / 3;
  overflow: hidden;
  flex: 0 0 auto;
}
.loom-book-cover-bare {
  inline-size: 4.5rem;
}
.loom-book-body {
  flex: 1 1 auto;
  min-inline-size: 0;
}
@container (min-width: 32rem) {
  .loom-book-frame {
    flex-direction: row;
    align-items: flex-start;
    gap: var(--loom-spacing-5);
  }
  .loom-book-cover {
    flex: 0 0 7rem;
  }
}
.loom-listing-media {
  position: relative;
  aspect-ratio: 4 / 3;
  overflow: hidden;
}
.loom-listing-flags {
  position: absolute;
  inset-block-start: var(--loom-spacing-3);
  inset-inline-start: var(--loom-spacing-3);
  display: flex;
  flex-wrap: wrap;
  align-items: center;
}
.loom-listing-flags:empty {
  display: none;
}
.loom-listing-media-bare {
  aspect-ratio: auto;
}
.loom-listing-media-bare .loom-listing-flags {
  position: static;
  padding: var(--loom-spacing-3);
}
.loom-listing-specs {
  display: flex;
  flex-wrap: wrap;
  align-items: baseline;
  column-gap: var(--loom-spacing-2);
  row-gap: var(--loom-spacing-1);
}
.loom-listing-specs:empty {
  display: none;
}
.loom-spec {
  display: inline-flex;
  align-items: baseline;
  gap: var(--loom-spacing-1);
}
.loom-spec:not(:last-child)::after {
  content: "·";
  margin-inline-start: var(--loom-spacing-1);
  color: var(--loom-fg-subtle);
}
.loom-trail-crumb {
  display: inline-flex;
  align-items: center;
  gap: var(--loom-spacing-2);
}
.loom-trail > .loom-trail-crumb + .loom-trail-crumb::before {
  flex: 0 0 auto;
  color: var(--loom-fg-subtle);
}
.loom-trail-chevron > .loom-trail-crumb + .loom-trail-crumb::before {
  content: "";
  width: 0.3em;
  height: 0.3em;
  border-block-start: 1px solid var(--loom-border-default);
  border-inline-end: 1px solid var(--loom-border-default);
  transform: rotate(45deg);
}
.loom-trail-slash > .loom-trail-crumb + .loom-trail-crumb::before {
  content: "/";
}
.loom-trail-dot > .loom-trail-crumb + .loom-trail-crumb::before {
  content: "\\00B7";
}
.loom-carousel {
  display: flex;
  align-items: stretch;
  overflow-x: auto;
  scroll-snap-type: inline mandatory;
  scroll-behavior: smooth;
  overscroll-behavior-inline: contain;
  scrollbar-width: thin;
  scrollbar-color: var(--loom-border-default) transparent;
  padding-block: var(--loom-spacing-2);
}
.loom-carousel:focus-visible {
  outline: 2px solid var(--loom-accent);
  outline-offset: 2px;
}
.loom-carousel-cell {
  display: flex;
  scroll-snap-align: start;
}
.loom-carousel-cell > * {
  width: 100%;
}
.loom-carousel-centred > .loom-carousel-cell {
  scroll-snap-align: center;
}
.loom-meter-fill {
  width: var(--loom-meter-sweep);
}
.loom-meter-fill, .loom-meter-arc {
  animation: loom-meter-sweep calc(var(--loom-motion-slow) * 2) cubic-bezier(0.22, 1, 0.36, 1) both;
}
@property --loom-halo-angle {
  syntax: "<angle>";
  inherits: false;
  initial-value: 135deg;
}
@keyframes loom-halo-trace {
  to { --loom-halo-angle: 495deg; }
}
.loom-halo-ring, .loom-halo-trace {
  border: 2px solid var(--loom-border-accent);
}
@supports ((mask-composite: exclude) or (-webkit-mask-composite: xor)) {
  .loom-halo-ring, .loom-halo-trace {
    border: 0;
    padding: 2px;
    background-image: linear-gradient(135deg, var(--loom-accent-strong), var(--loom-brand-secondary));
    -webkit-mask: linear-gradient(black 0 0) content-box, linear-gradient(black 0 0);
    -webkit-mask-composite: xor;
    mask: linear-gradient(black 0 0) content-box, linear-gradient(black 0 0);
    mask-composite: exclude;
  }
  .loom-halo-trace {
    background-image: conic-gradient(from var(--loom-halo-angle, 135deg), var(--loom-brand-secondary), var(--loom-accent-strong), var(--loom-brand-secondary));
    animation: loom-halo-trace calc(var(--loom-motion-slow) * 8) linear infinite;
  }
}
.loom-washed {
  color: var(--loom-accent-strong);
}
@supports ((background-clip: text) or (-webkit-background-clip: text)) {
  .loom-washed {
    background-image: linear-gradient(100deg, var(--loom-accent-strong), var(--loom-brand-secondary));
    -webkit-background-clip: text;
    background-clip: text;
    color: transparent;
    -webkit-text-fill-color: transparent;
  }
}
@media (forced-colors: active) {
  .loom-washed {
    background-image: none;
    color: currentColor;
    -webkit-text-fill-color: currentColor;
  }
}
.loom-stat {
  display: flex;
  flex-direction: column;
  gap: var(--loom-spacing-1);
  container-type: inline-size;
}
.loom-stat-value {
  font-family: var(--loom-heading-family);
  font-weight: var(--loom-heading-weight);
  font-size: min(var(--loom-scale-7), 26cqi);
  line-height: 1.05;
  color: var(--loom-accent);
}
.loom-stat-label {
  font-family: var(--loom-body-family);
  font-size: var(--loom-scale-3);
  color: var(--loom-fg-default);
}
.loom-stat-caption {
  font-family: var(--loom-body-family);
  font-size: var(--loom-scale-2);
  color: var(--loom-fg-muted);
}
.loom-stat-chart {
  display: grid;
  grid-auto-flow: column;
  grid-auto-columns: minmax(0, 1fr);
  align-items: end;
  gap: var(--loom-spacing-3);
  border-bottom: 1px solid var(--loom-border-default);
  padding-bottom: var(--loom-spacing-2);
}
.loom-stat-chart > .loom-stat {
  display: grid;
  grid-template-rows: var(--loom-chart-plot) auto auto;
  align-items: end;
  gap: var(--loom-spacing-1);
  min-width: 0;
}
.loom-stat-chart > .loom-stat-plotted::before {
  content: "";
  display: block;
  align-self: end;
  width: 100%;
  border-radius: var(--loom-radius-sm) var(--loom-radius-sm) 0 0;
  background-image: linear-gradient(to top, var(--loom-accent-strong), var(--loom-brand-secondary));
  height: calc(var(--loom-chart-plot) * min(1, max(0, var(--loom-stat-magnitude, 0) / var(--loom-chart-max, 100))));
}
.loom-stat-chart > .loom-stat > .loom-stat-value {
  font-size: var(--loom-scale-4);
}
.loom-stat-chart > .loom-stat > .loom-stat-label {
  font-size: var(--loom-scale-2);
  color: var(--loom-fg-muted);
  overflow-wrap: anywhere;
}
@media (prefers-reduced-motion: reduce) {
  .loom-halo-trace {
    animation: none;
  }
  .loom-orbit-spinner, .loom-orbit-item {
    animation: none;
  }
  .loom-message-dot {
    animation: none;
    opacity: 1;
    transform: none;
  }
  .loom-reveal:not(.loom-reveal-still) {
    animation: none;
    opacity: 1;
    transform: none;
  }
  .loom-pin-dot::after {
    animation: none;
  }
  .loom-rise, .loom-aurora {
    animation: none;
    opacity: 1;
    transform: none;
  }
  .loom-marquee {
    -webkit-mask-image: none;
    mask-image: none;
  }
  .loom-marquee-track {
    animation: none;
    display: block;
    width: auto;
  }
  .loom-marquee-run {
    flex-wrap: wrap;
    padding-inline-end: 0;
  }
  .loom-marquee-echo {
    display: none;
  }
  .loom-lift, .loom-underline, .loom-marker, .loom-mark, .loom-input, .loom-compare-row > *, .loom-table-row > *, .loom-recording-play, .loom-pager .loom-link {
    transition: none;
  }
  /**
   * The sweep goes and the bar stays. Unlike an entrance, a waiting state with
   * no animation is still saying the whole of what it says — the shape is the
   * message — so this one is dropped outright rather than parked at its end.
   */
  .loom-waiting-bar {
    animation: none;
    background: var(--loom-bg-surface-muted);
  }
  .loom-lift:hover {
    transform: none;
  }
  .loom-menu-panel > * {
    transition: none;
  }
  .loom-meter-fill, .loom-meter-arc {
    animation: none;
  }
  .loom-carousel {
    scroll-behavior: auto;
  }
  .loom-recording:hover .loom-recording-play, .loom-recording:focus-within .loom-recording-play {
    transform: translate(-50%, -50%);
  }
}
`.trim()

/**
 * Emitted beside a primitive's own root element rather than around it, for the
 * reason `editable.ts` gives for never wrapping: a wrapper changes what `>`,
 * `:first-child` and `:nth-child` select. A hoisted `<style>` is removed from
 * the flow entirely, and an un-hoisted one is a metadata element siblings do
 * not count.
 */
export const libraryStylesheet = (): ReactElement =>
  createElement("style", {
    href: STYLESHEET_HREF,
    precedence: STYLESHEET_PRECEDENCE,
    children: CSS,
  })
