import { createElement, type ReactElement } from "react"

/**
 * The one stylesheet this library emits, and the reason there is one at all.
 *
 * Every other value a primitive uses is an inline style, which is what keeps a
 * render a pure function of the tree with nothing to attach and nothing to load.
 * Five things cannot be said inline, and the first three are the difference
 * between a primitive that looks like a UI kit and one that looks like a
 * product:
 *
 * - **keyframes** — an entrance, a drift, a marquee
 * - **state selectors** — `:hover`, `:focus-visible`, `details[open]`,
 *   `[aria-current="page"]`. The last one is a state the *tree* sets rather
 *   than the reader, and it is here for the same reason as the others: a link
 *   that says which page you are on has to be marked with the mark hovering
 *   already makes, and one element cannot hold two values of one property.
 * - **`prefers-reduced-motion`** — the one media query that is not a layout
 *   decision, and honouring it is not optional
 * - **pseudo-elements** — `::after`. A card whose title anchor covers the whole
 *   surface is one overlay generated by that anchor; the alternative is a
 *   second element in the markup that exists only to be clicked.
 * - **position selectors** — `:last-child`, `:first-of-type`. A render is a
 *   pure function of one node, so no primitive can know it is the last of its
 *   siblings; a rail that must stop at the final dot, or a grid that runs its
 *   lead piece across the top, has nowhere else to be said.
 *
 * That last one is ordinary CSS doing what only CSS can, and it needs no more
 * justification than `:hover` does — where a primitive sits among its siblings
 * is the browser's business, and how a primitive is styled is simply part of
 * what that primitive *is*. Two mechanics are worth knowing before writing one,
 * though, because all three are easy to get wrong once and hard to see
 * afterwards:
 *
 * 1. **An inline style beats a rule here**, always. A primitive that sets a
 *    property inline has made that property unreachable from this file, so a
 *    value the stylesheet needs to vary — `loom.milestone`'s bottom gap — must
 *    not also be set on the element.
 * 2. **Scope every selector to a library class.** `li:last-child` would reach
 *    every list on the host's page; `.loom-rail > li:last-child` reaches only
 *    the one this library drew.
 * 3. **A missing `}` deletes the rule after it, silently.** This is a template
 *    literal rather than a parsed stylesheet, so nothing here or in a test
 *    noticed when the comparison band's last rule shipped unclosed on 22 August
 *    and swallowed `.loom-list { margin: 0 }` whole — CSS error recovery treats
 *    the next rule as one bad declaration, drops it, and carries on rendering
 *    everything else correctly. Every list in the library carried the browser's
 *    default margins for a day and no assertion could see it. `library.test.ts`
 *    now parses this text and holds every block closed; do not weaken that test
 *    to add a rule it complains about.
 *
 * So a primitive that needs any of them emits this element beside its own root.
 * It is static text: no prop reaches it, nothing is interpolated into it, and it
 * is byte-identical under every theme because every value in it is a `var()`.
 * That matters more than it looks — it is what keeps 0049's re-theme guarantee
 * true for animated primitives, and it is why an AI proposal cannot reach the
 * animation. The tree configures content, variant and theme; motion is part of
 * the implementation the registry vouches for, which is the bargain in 0007
 * working exactly as intended.
 *
 * React 19 dedupes and hoists a `<style>` carrying `href` and `precedence`, so
 * twenty animated primitives on one page emit one stylesheet in the document
 * head. A renderer that does not hoist emits identical copies, which are inert.
 */

export const STYLESHEET_HREF = "loom-primitives"
export const STYLESHEET_PRECEDENCE = "loom"

/** Class names the library's primitives apply. Exported so a test can name them. */
export const LIBRARY_CLASS = {
  /** Fades and lifts into place once, on entry. Stagger with `animationDelay`. */
  rise: "loom-rise",
  /** Raises a card on hover, and marks it as a surface that responds. */
  lift: "loom-lift",
  /** Wipes an underline in from the left on hover — a link that is a whole tile. */
  underline: "loom-underline",
  /** Two slow-drifting colour fields, for a hero backdrop that is not a flat wash. */
  aurora: "loom-aurora",
  /** The disclosure marker of a `details`, rotated when its section is open. */
  marker: "loom-marker",
  /** A logo held back to grey until it is pointed at. */
  mark: "loom-mark",
  /** A `loom.milestone-list`: spaces its entries and ends its own rail. */
  rail: "loom-rail",
  /** The same list, set tighter — a changelog to scan rather than a history to read. */
  railTight: "loom-rail-tight",
  /** The same list with the connecting line dropped, dots kept. */
  railNone: "loom-rail-none",
  /** One entry's connector, hidden on the last entry because only CSS knows which that is. */
  railLine: "loom-rail-line",
  /** One entry's content cell, which carries the gap to the entry below it. */
  railBody: "loom-rail-body",
  /** A card whose title anchor is stretched over the whole surface. */
  cover: "loom-cover",
  /** That anchor. Its `::after` is what makes the surface clickable. */
  coverLink: "loom-cover-link",
  /** A card's cover image, cropped to a ratio the card owns rather than the file does. */
  coverMedia: "loom-cover-media",
  /** A card's padded interior, so a lead layout can set it beside the cover. */
  coverBody: "loom-cover-body",
  /** A `loom.article-grid` running its first piece across the top. */
  lead: "loom-lead",
  /** One `loom.field`. Named so the form it sits in can size it in a row. */
  field: "loom-field",
  /** Any control inside a field: the focus ring, the hover, the placeholder. */
  input: "loom-input",
  /** The wrapper that draws a select's chevron, since the native one is not the palette's. */
  select: "loom-select",
  /** A `loom.form` laid out as a single row — see the rule about sizing children. */
  formInline: "loom-form-inline",
  /**
   * A `loom.avatar-row` cluster: each face overlaps the one before it and rings
   * itself in the page's ground so the edge reads. The ring is `bg-canvas`
   * because a primitive cannot know what it is sitting on — a cluster placed
   * inside a `loom.card` rings itself in the canvas colour rather than the
   * card's, which is a hair off and the honest limit of a static stylesheet.
   */
  cluster: "loom-cluster",
  /** A `loom.comparison-table`'s `<table>`: separators, padding, and the featured column. */
  compare: "loom-compare",
  /** The same table set as a spec to scan rather than a page to read. */
  compareTight: "loom-compare-tight",
  /** One `loom.comparison-row`, so the whole row can answer a pointer. */
  compareRow: "loom-compare-row",
  /** Its leading cell — the criterion, which stays put while the band scrolls. */
  compareKey: "loom-compare-key",
  /** A qualifier under an answer, dimmed — and re-lit where the column is tinted. */
  compareNote: "loom-compare-note",
  /**
   * The three verdicts. Their colour is here rather than on the element because
   * a tinted column re-inks the two that recede — `fg-subtle` on `accent-subtle`
   * measures 3.76:1 across the registered palettes, under the bar 0074 holds a
   * text slot to — and an inline colour would beat the rule that does it.
   */
  compareYes: "loom-compare-yes",
  compareNo: "loom-compare-no",
  comparePartial: "loom-compare-partial",
  /**
   * The subject column a page is steering towards, by position. A column is
   * not a node (0084), so this is the only handle it has — and four of them,
   * because each is a static rule rather than an interpolated index.
   */
  compareFeatureFirst: "loom-compare-feature-1",
  compareFeatureSecond: "loom-compare-feature-2",
  compareFeatureThird: "loom-compare-feature-3",
  compareFeatureFourth: "loom-compare-feature-4",
  /**
   * A `loom.list`: its markers take the accent, and its rows carry the gap
   * between them. Both are here rather than inline because neither is
   * expressible on the element that needs it — `::marker` is a pseudo-element,
   * and a row's gap is a fact about the *list* that only the row can apply.
   */
  list: "loom-list",
  /** The same list set tight — points to scan rather than points to read. */
  listTight: "loom-list-tight",
  /** The same list set loose, for rows that are a sentence each. */
  listLoose: "loom-list-loose",
  /**
   * A `loom.table`: the padding its cells share, and the rules between its
   * rows. Both are the *table's* decisions applied to cells it does not render,
   * which is the one thing an inline style cannot reach.
   */
  table: "loom-table",
  /** The same table drawn as a bordered surface, which is what makes its heading column stick. */
  tablePanel: "loom-table-panel",
  /** The same table set tight — a spec to scan — and set loose, a page to read. */
  tableTight: "loom-table-tight",
  tableLoose: "loom-table-loose",
  /** Vertical rules as well as horizontal ones, and no rules at all. */
  tableGrid: "loom-table-grid",
  tableFlush: "loom-table-flush",
  /** One `loom.table-row`, so the whole row can answer a pointer. */
  tableRow: "loom-table-row",
  /** A row the page is pointing at, which keeps its tint under that pointer. */
  tableHighlight: "loom-table-highlight",
  /** A `loom.table-cell` heading a row, which stays put while a panel scrolls. */
  tableKey: "loom-table-key",
  /**
   * A `loom.marquee`. The band that clips; the track that travels; the run of
   * items; the second, decorative run that makes the loop seamless; the
   * direction, the edge fade, and the still rendering the band takes while
   * somebody is editing it.
   *
   * Everything about the track is here rather than on the element, and that is
   * load-bearing rather than tidy: its duration is chosen by how many items the
   * run holds, its width and its animation are cancelled by the still variant
   * and again by reduced motion, and an inline style would beat all three.
   */
  marquee: "loom-marquee",
  marqueeTrack: "loom-marquee-track",
  marqueeRun: "loom-marquee-run",
  marqueeEcho: "loom-marquee-echo",
  marqueeReverse: "loom-marquee-reverse",
  marqueeFaded: "loom-marquee-faded",
  marqueeStill: "loom-marquee-still",
  /**
   * A `loom.offering`. The card declares the containment; the frame inside it
   * is what the `@container` rule flips from a column into a row, because a
   * container query reads its *ancestor* and never the element that declared it.
   *
   * Everything about the frame's direction, the body's growth and the action's
   * `auto` start margin is here rather than on the element, and that is
   * load-bearing rather than tidy: the row layout cancels the margin, and an
   * inline style would beat the rule that does it.
   */
  offering: "loom-offering",
  offeringFrame: "loom-offering-frame",
  offeringBody: "loom-offering-body",
  offeringAction: "loom-offering-action",
  /** A `loom.credential`: the positioned ancestor its stretched name anchor needs. */
  credential: "loom-credential",
  /**
   * A `loom.nav`. The bar itself, the box holding its disclosure control, and
   * the menu that control opens and closes.
   *
   * The menu's `display` is here rather than on the element, and that is the
   * whole reason the disclosure works at all: 0092's contract is a rule that
   * hides the region, and an inline `display: flex` would beat it. Its
   * alignment stays inline, because that varies by prop and nothing needs to
   * override it.
   *
   * The drawer aligns its items to `flex-start` rather than stretching them,
   * and that is a rendering decision rather than a tidiness one: the current
   * item is marked by an underline the link paints across its own box, so a
   * stretched row draws that rule the full width of the bar. One mark that
   * renders as a text underline on a laptop and as a full-width rule on a
   * phone is the same primitive saying two different things.
   */
  nav: "loom-nav",
  navToggle: "loom-nav-toggle",
  navMenu: "loom-nav-menu",
  /** Its actions end, which takes the slack on a phone when no control was built. */
  navActions: "loom-nav-actions",
  /** A `loom.mosaic`: one column until there is room for six. */
  mosaic: "loom-mosaic",
  /** Its three rhythms, each a cycle of spans that fills a six-column row exactly. */
  mosaicAlternating: "loom-mosaic-alternating",
  mosaicShowcase: "loom-mosaic-showcase",
  mosaicLead: "loom-mosaic-lead",
} as const

/**
 * Reduced motion removes movement, never feedback: a `.loom-rise` element ends
 * at `opacity: 1` rather than never arriving, and hover still recolours. An
 * entrance animation that is simply switched off is how a page renders blank
 * for anyone who asked their system to calm it down.
 */
const CSS = `
@keyframes loom-rise {
  from { opacity: 0; transform: translate3d(0, 0.9rem, 0); }
  to { opacity: 1; transform: none; }
}
@keyframes loom-aurora {
  0% { transform: translate3d(-6%, -4%, 0) scale(1); }
  50% { transform: translate3d(6%, 4%, 0) scale(1.25); }
  100% { transform: translate3d(-6%, -4%, 0) scale(1); }
}
.loom-rise {
  animation: loom-rise calc(var(--loom-motion-slow) * 1.6) cubic-bezier(0.22, 1, 0.36, 1) both;
}
.loom-lift {
  transition: transform var(--loom-motion-medium) ease, box-shadow var(--loom-motion-medium) ease, border-color var(--loom-motion-medium) ease;
}
.loom-lift:hover {
  transform: translate3d(0, -4px, 0);
  box-shadow: 0 24px 48px -34px var(--loom-fg-default);
  border-color: var(--loom-border-accent);
}
.loom-underline {
  background-image: linear-gradient(var(--loom-accent), var(--loom-accent));
  background-repeat: no-repeat;
  background-position: 0 100%;
  background-size: 0% 2px;
  transition: background-size var(--loom-motion-medium) cubic-bezier(0.22, 1, 0.36, 1);
}
.loom-underline:hover, .loom-underline:focus-visible {
  background-size: 100% 2px;
}
.loom-underline[aria-current="page"] {
  background-size: 100% 2px;
}
.loom-aurora {
  animation: loom-aurora calc(var(--loom-motion-slow) * 40) ease-in-out infinite;
}
.loom-marker {
  transition: transform var(--loom-motion-medium) cubic-bezier(0.22, 1, 0.36, 1);
}
details[open] > summary .loom-marker {
  transform: rotate(45deg);
}
.loom-mark {
  filter: grayscale(1);
  opacity: 0.72;
  transition: filter var(--loom-motion-medium) ease, opacity var(--loom-motion-medium) ease;
}
.loom-mark:hover, a:hover > .loom-mark, a:focus-visible > .loom-mark {
  filter: none;
  opacity: 1;
}
.loom-rail > li .loom-rail-body {
  padding-block-end: var(--loom-spacing-5);
}
.loom-rail-tight > li .loom-rail-body {
  padding-block-end: var(--loom-spacing-3);
}
.loom-rail > li:last-child .loom-rail-body {
  padding-block-end: 0;
}
.loom-rail > li:last-child .loom-rail-line, .loom-rail-none .loom-rail-line {
  visibility: hidden;
}
.loom-cover {
  position: relative;
  flex-direction: column;
}
.loom-cover > .loom-cover-body {
  flex: 1 1 auto;
}
.loom-cover-link::after {
  content: "";
  position: absolute;
  inset: 0;
}
.loom-cover-media {
  aspect-ratio: 16 / 10;
  overflow: hidden;
}
.loom-lead > article:first-of-type {
  grid-column: 1 / -1;
  flex-direction: row;
  flex-wrap: wrap;
}
.loom-lead > article:first-of-type > .loom-cover-media,
.loom-lead > article:first-of-type > .loom-cover-body {
  flex: 1 1 20rem;
}
.loom-lead > article:first-of-type > .loom-cover-media {
  aspect-ratio: auto;
  min-height: 16rem;
}
.loom-input {
  transition: border-color var(--loom-motion-medium) ease;
}
.loom-input:hover {
  border-color: var(--loom-border-strong);
}
.loom-input:focus-visible {
  outline: 2px solid var(--loom-border-accent);
  outline-offset: 2px;
  border-color: var(--loom-border-accent);
}
.loom-input::placeholder {
  color: var(--loom-fg-muted);
  opacity: 1;
}
.loom-input:disabled {
  cursor: not-allowed;
}
.loom-select::after {
  content: "";
  position: absolute;
  inset-inline-end: var(--loom-spacing-3);
  inset-block-start: 50%;
  width: 0.42em;
  height: 0.42em;
  border-inline-end: 2px solid currentColor;
  border-block-end: 2px solid currentColor;
  transform: translate3d(0, -70%, 0) rotate(45deg);
  color: var(--loom-fg-muted);
  pointer-events: none;
}
.loom-form-inline > .loom-field {
  flex: 1 1 14rem;
}
.loom-cluster > * + * {
  margin-inline-start: -0.7em;
}
.loom-cluster > * {
  box-shadow: 0 0 0 2px var(--loom-bg-canvas);
}
.loom-compare th, .loom-compare td {
  padding: var(--loom-spacing-3) var(--loom-spacing-4);
}
.loom-compare-tight th, .loom-compare-tight td {
  padding: var(--loom-spacing-2) var(--loom-spacing-3);
}
.loom-compare thead > tr > * {
  border-block-end: 1px solid var(--loom-border-strong);
}
.loom-compare tbody > tr + tr > * {
  border-block-start: 1px solid var(--loom-border-subtle);
}
.loom-compare-key {
  position: sticky;
  inset-inline-start: 0;
  background: var(--loom-bg-surface);
  z-index: 1;
}
.loom-compare-row > * {
  transition: background-color var(--loom-motion-medium) ease;
}
.loom-compare-row:hover > * {
  background: var(--loom-bg-surface-muted);
}
.loom-compare-note, .loom-compare-no {
  color: var(--loom-fg-subtle);
}
.loom-compare-yes {
  color: var(--loom-accent-strong);
}
.loom-compare-partial {
  color: var(--loom-fg-muted);
}
.loom-compare-feature-1 tr > *:nth-child(2),
.loom-compare-feature-2 tr > *:nth-child(3),
.loom-compare-feature-3 tr > *:nth-child(4),
.loom-compare-feature-4 tr > *:nth-child(5) {
  background: var(--loom-accent-subtle);
  border-inline: 1px solid var(--loom-border-accent);
}
.loom-compare-feature-1 tr > *:nth-child(2) .loom-compare-note,
.loom-compare-feature-2 tr > *:nth-child(3) .loom-compare-note,
.loom-compare-feature-3 tr > *:nth-child(4) .loom-compare-note,
.loom-compare-feature-4 tr > *:nth-child(5) .loom-compare-note,
.loom-compare-feature-1 tr > *:nth-child(2) .loom-compare-no,
.loom-compare-feature-2 tr > *:nth-child(3) .loom-compare-no,
.loom-compare-feature-3 tr > *:nth-child(4) .loom-compare-no,
.loom-compare-feature-4 tr > *:nth-child(5) .loom-compare-no {
  color: var(--loom-fg-muted);
}
.loom-list {
  margin: 0;
}
.loom-list > li::marker {
  color: var(--loom-accent);
}
.loom-list > li + li {
  margin-block-start: var(--loom-spacing-2);
}
.loom-list-tight > li + li {
  margin-block-start: var(--loom-spacing-1);
}
.loom-list-loose > li + li {
  margin-block-start: var(--loom-spacing-4);
}
.loom-list .loom-list {
  margin-block-start: var(--loom-spacing-2);
}
.loom-table th, .loom-table td {
  padding: var(--loom-spacing-3) var(--loom-spacing-4);
}
.loom-table-tight th, .loom-table-tight td {
  padding: var(--loom-spacing-2) var(--loom-spacing-3);
}
.loom-table-loose th, .loom-table-loose td {
  padding: var(--loom-spacing-4) var(--loom-spacing-5);
}
.loom-table thead > tr > * {
  border-block-end: 1px solid var(--loom-border-strong);
}
.loom-table tbody > tr + tr > * {
  border-block-start: 1px solid var(--loom-border-subtle);
}
.loom-table-grid tr > * + * {
  border-inline-start: 1px solid var(--loom-border-subtle);
}
.loom-table-flush thead > tr > *, .loom-table-flush tbody > tr + tr > * {
  border-block: 0;
}
.loom-table-row > * {
  transition: background-color var(--loom-motion-medium) ease;
}
.loom-table-row:hover > * {
  background: var(--loom-bg-surface-muted);
}
.loom-table-highlight > * {
  background: var(--loom-accent-subtle);
}
.loom-table-panel .loom-table-key {
  position: sticky;
  inset-inline-start: 0;
  background: var(--loom-bg-surface);
  z-index: 1;
}
.loom-table-panel .loom-table-highlight .loom-table-key {
  background: var(--loom-accent-subtle);
}
@keyframes loom-marquee {
  from { transform: translate3d(0, 0, 0); }
  to { transform: translate3d(-50%, 0, 0); }
}
.loom-marquee {
  container-type: inline-size;
}
.loom-marquee-run > * {
  max-inline-size: min(32rem, 80cqi);
}
.loom-marquee-track {
  display: flex;
  width: max-content;
  animation: loom-marquee calc(var(--loom-motion-slow) * 9) linear infinite;
}
.loom-marquee-run {
  display: flex;
  flex: 0 0 auto;
  align-items: center;
}
.loom-marquee-reverse {
  animation-direction: reverse;
}
.loom-marquee-faded {
  -webkit-mask-image: linear-gradient(to right, transparent 0, black 8%, black 92%, transparent 100%);
  mask-image: linear-gradient(to right, transparent 0, black 8%, black 92%, transparent 100%);
}
.loom-marquee:hover .loom-marquee-track, .loom-marquee:focus-within .loom-marquee-track {
  animation-play-state: paused;
}
.loom-marquee-track:has(> * > :nth-child(2)) { animation-duration: calc(var(--loom-motion-slow) * 18); }
.loom-marquee-track:has(> * > :nth-child(3)) { animation-duration: calc(var(--loom-motion-slow) * 27); }
.loom-marquee-track:has(> * > :nth-child(4)) { animation-duration: calc(var(--loom-motion-slow) * 36); }
.loom-marquee-track:has(> * > :nth-child(5)) { animation-duration: calc(var(--loom-motion-slow) * 45); }
.loom-marquee-track:has(> * > :nth-child(6)) { animation-duration: calc(var(--loom-motion-slow) * 54); }
.loom-marquee-track:has(> * > :nth-child(7)) { animation-duration: calc(var(--loom-motion-slow) * 63); }
.loom-marquee-track:has(> * > :nth-child(8)) { animation-duration: calc(var(--loom-motion-slow) * 72); }
.loom-marquee-track:has(> * > :nth-child(9)) { animation-duration: calc(var(--loom-motion-slow) * 81); }
.loom-marquee-track:has(> * > :nth-child(10)) { animation-duration: calc(var(--loom-motion-slow) * 90); }
.loom-marquee-track:has(> * > :nth-child(11)) { animation-duration: calc(var(--loom-motion-slow) * 99); }
.loom-marquee-track:has(> * > :nth-child(12)) { animation-duration: calc(var(--loom-motion-slow) * 108); }
.loom-marquee-track:has(> * > :nth-child(13)) { animation-duration: calc(var(--loom-motion-slow) * 117); }
.loom-marquee-track:has(> * > :nth-child(14)) { animation-duration: calc(var(--loom-motion-slow) * 126); }
.loom-marquee-track:has(> * > :nth-child(15)) { animation-duration: calc(var(--loom-motion-slow) * 135); }
.loom-marquee-track:has(> * > :nth-child(16)) { animation-duration: calc(var(--loom-motion-slow) * 144); }
.loom-marquee-still {
  -webkit-mask-image: none;
  mask-image: none;
}
.loom-marquee-still .loom-marquee-track {
  animation: none;
  display: block;
  width: auto;
}
.loom-marquee-still .loom-marquee-run {
  flex-wrap: wrap;
}
.loom-offering {
  container-type: inline-size;
}
.loom-offering-frame {
  display: flex;
  flex-direction: column;
  gap: var(--loom-spacing-4);
  height: 100%;
}
.loom-offering-body {
  flex: 1 1 auto;
  min-inline-size: 0;
}
.loom-offering-action {
  display: grid;
  margin-block-start: auto;
}
@container (min-width: 40rem) {
  .loom-offering-frame {
    flex-direction: row;
    align-items: center;
    gap: var(--loom-spacing-5);
  }
  .loom-offering-action {
    flex: 0 0 auto;
    margin-block-start: 0;
  }
}
.loom-credential {
  position: relative;
}
.loom-nav-menu {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--loom-spacing-5);
}
.loom-nav-toggle {
  display: none;
}
.loom-nav-toggle:empty {
  display: none;
}
@media (max-width: 47.99rem) {
  .loom-nav-toggle {
    display: block;
    margin-inline-start: auto;
  }
  .loom-nav:not(:has(.loom-nav-toggle > *)) .loom-nav-actions {
    margin-inline-start: auto;
  }
  .loom-nav-menu {
    order: 1;
    flex-basis: 100%;
    flex-direction: column;
    align-items: flex-start;
    gap: var(--loom-spacing-3);
  }
  .loom-nav:has(.loom-nav-toggle [data-loom-disclosed="false"]) .loom-nav-menu {
    display: none;
  }
}
.loom-mosaic {
  display: grid;
  grid-template-columns: 1fr;
  align-items: stretch;
}
@media (min-width: 48rem) {
  .loom-mosaic {
    grid-template-columns: repeat(6, 1fr);
  }
  .loom-mosaic-alternating > *:nth-child(4n + 1),
  .loom-mosaic-alternating > *:nth-child(4n) {
    grid-column: span 4;
  }
  .loom-mosaic-alternating > *:nth-child(4n + 2),
  .loom-mosaic-alternating > *:nth-child(4n + 3) {
    grid-column: span 2;
  }
  .loom-mosaic-showcase > *:nth-child(5n + 1),
  .loom-mosaic-showcase > *:nth-child(5n + 2) {
    grid-column: span 3;
  }
  .loom-mosaic-showcase > *:nth-child(5n + 3),
  .loom-mosaic-showcase > *:nth-child(5n + 4),
  .loom-mosaic-showcase > *:nth-child(5n) {
    grid-column: span 2;
  }
  .loom-mosaic-lead > * {
    grid-column: span 2;
  }
  .loom-mosaic-lead > *:first-child {
    grid-column: span 6;
  }
}
@media (prefers-reduced-motion: reduce) {
  .loom-rise, .loom-aurora {
    animation: none;
    opacity: 1;
    transform: none;
  }
  .loom-marquee {
    -webkit-mask-image: none;
    mask-image: none;
  }
  .loom-marquee-track {
    animation: none;
    display: block;
    width: auto;
  }
  .loom-marquee-run {
    flex-wrap: wrap;
  }
  .loom-marquee-echo {
    display: none;
  }
  .loom-lift, .loom-underline, .loom-marker, .loom-mark, .loom-input, .loom-compare-row > *, .loom-table-row > * {
    transition: none;
  }
  .loom-lift:hover {
    transform: none;
  }
}
`.trim()

/**
 * Emitted beside a primitive's own root element rather than around it, for the
 * reason `editable.ts` gives for never wrapping: a wrapper changes what `>`,
 * `:first-child` and `:nth-child` select. A hoisted `<style>` is removed from
 * the flow entirely, and an un-hoisted one is a metadata element siblings do
 * not count.
 */
export const libraryStylesheet = (): ReactElement =>
  createElement("style", {
    href: STYLESHEET_HREF,
    precedence: STYLESHEET_PRECEDENCE,
    children: CSS,
  })
